### ISSUE TITLE
Styling can be improved. 

### ISSUE THREAD

**Issue by PYIArun** [Open-Code-Crafters/FitFlex#10]
I have noticed several areas that can be improved. Below, I will list them one by one:

1. Images are either not available or not loading in many parts of the site.  
![image](https://github.com/user-attachments/assets/69ba0fdc-bfa4-4176-9590-299b5e74d250)

2. The layout and text inside can be better aligned. For example, "Biceps Special" and "Super Biceps Special" can start from the left edge, while "30 Days Easy Level" can be aligned to the opposite edge instead of being centered in that card.  
![image](https://github.com/user-attachments/assets/5ff1aac5-2387-4c4c-953f-cc855b7d0bd6)

3. The elements in this section look very congested.  
![image](https://github.com/user-attachments/assets/a25e99fb-1e31-4b50-b0cb-6d40e1af93c3)  
(The text could be slightly smaller, and the spacing could be increased.)

4. Underline styling could be avoided, as it resembles a heading with a tagline below. Therefore, I think there is no need to apply underlining in this case; instead, the heading font could be slightly bolder.  
![image](https://github.com/user-attachments/assets/6f3764e6-e320-495a-8652-72f69a00c393)

I would like to work on points you agreed with, and I kindly request that you assign me this task under GSSOC Extended Contribution '24. Thank you!

**Comment by jeevan10017** [comment]
@PYIArun go ahead
