### ISSUE TITLE
[Feature Request]: Adding Multi-language Support in FitFlex

### ISSUE THREAD

**Issue by IkkiOcean** [Open-Code-Crafters/FitFlex#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We need to integrate Google Translator into the Rentalog web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Use Case

Allow users to translate all pages of the FitFlex application into their preferred language using Google Translator.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by IkkiOcean** [comment]
Please make it atleast level 3

**Comment by jeevan10017** [comment]
@IkkiOcean go ahead. I may decrease your level of contribution based on the quality of your work in PR.
