### ISSUE TITLE
Inconsistent Branding: Mismatch Between Logo and Site Name

### ISSUE THREAD

**Issue by SCR01** [Open-Code-Crafters/FitFlex#11]
The logo says **"FitFlux"** while the site name and header display **"FitFlex."** This creates confusion for users as to the actual name of the brand. The logo and site name should be consistent across the platform to reinforce branding and avoid confusion

![issue](https://github.com/user-attachments/assets/07b5faba-88ee-44e4-b768-f6b121864f5c)

**Suggested Solution:**

 Update the logo to "FitFlex" to ensure the uniformity.

**Comment by jeevan10017** [comment]
@SCR01 Do you want to work for it?

**Comment by SCR01** [comment]
@jeevan10017 Yeah, I think changing the logo with the brand name suits the site better.

**Comment by jeevan10017** [comment]
> @jeevan10017 Yeah, I think changing the logo with the brand name, suits the site better.

Are you working on it?

**Comment by SCR01** [comment]
@jeevan10017 Not yet, but I can redesign the logo.

**Comment by jeevan10017** [comment]
@SCR01 Go ahead
