### ISSUE TITLE
[Feature Request]: Redesign the Footer (Template with not working icons now )

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/92af07da-b5c7-4f6a-afb0-c17ef2f63cb0)

### Use Case

The current footer doesnt work . because the tags are not connected to the website, so it will redesign the footer and do all nessecary integrations across all the pages of the website  

### Add ScreenShots

![image](https://github.com/user-attachments/assets/4d707ad6-b973-4fe0-b35b-c6e38a120237)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@samar12-rad go ahead
