### ISSUE TITLE
Fix the sliders on the Home Page 

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The sliders on the page are broken because some javascript code, and showing unusual behaviour, i will fix it. Assign it to me now 

### Use Case

It will imporve overall UI of the website.

### Add ScreenShots

https://github.com/user-attachments/assets/470e7921-0fe0-47b6-ba00-67a0cff80f0b

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@samar12-rad someone is working on it. Kindly refer all the issues, before you raise new one.
