### ISSUE TITLE
Fixing The Mobiile UI

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The mobile ui of the website has some white line line comming in the right of the screen, and the images are also not alligned prooperly.

### Use Case

I will fix thses so the website becomes usable on the phone screen layout also 

### Add ScreenShots

https://github.com/user-attachments/assets/7834a7cb-4787-4feb-977e-d8c0f89ad848

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@samar12-rad its too resolved
