### ISSUE TITLE
[Feature Request]: Create Login Form for FitFlex Website

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Description: The FitFlex website currently has a registration form, but a login form needs to be created to allow existing users to access their accounts. The login form should be user-friendly and consistent with the overall design of the website.

Requirements:

Form Fields:
Email address input (with proper validation).
Password input (with password visibility toggle).

"Forgot Password" link that redirects to the password recovery page.
Submit button to authenticate user credentials.
Design:
Ensure the login form matches the design aesthetics of the existing registration form.
Make it fully responsive for both desktop and mobile devices.

### Use Case

The users can currently login, but that doesn't do anything, right now .

### Add ScreenShots

![image](https://github.com/user-attachments/assets/2e82689c-9c80-42ca-a547-cba4bac4b9c6)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@samar12-rad this website exists a login form. Kindly resolve this page not found issue.

**Comment by samar12-rad** [comment]
ok

**Comment by sameer-soni** [comment]
@jeevan10017 If there's no update, can I get assigned to this issue?

**Comment by samar12-rad** [comment]
@jeevan10017 I am working on it.
