### ISSUE TITLE
[Feature Request]: Create a profile Dashboard for the Users signed in 

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create a profile dashboard for the users, There is nothing happens when user logs in the website. The profile page is empty, and meses up the ui 

### Use Case

The users and login features of the website will have some meaning after this imlemented, Users will be able to see there score and other information , ther fav coursess , etc. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9aee950f-95ed-49cd-b8de-5ee9d6c443ba)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@samar12-rad go ahead. display all the images(registered through Google auth) and details that he/she entered while registering.including mail, phone, dob, height, weight. also, give the edit option to all of it.

**Comment by jeevan10017** [comment]
@samar12-rad If you aware of doing thing, kindly tag me and message, so i can assign you for this.

**Comment by jeevan10017** [comment]
@samar12-rad hello. Kindly react upper message

**Comment by samar12-rad** [comment]
Yes, i will do it

**Comment by samar12-rad** [comment]
pls assign me this @jeevan10017
