### ISSUE TITLE
Footer's Alignment correction

### ISSUE THREAD

**Issue by awezmirza** [Open-Code-Crafters/FitFlex#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/734a9435-d331-45ed-8400-e8cbf7183f42)
The footer section is not aligned properly

### Use Case

Fixing this will give a beeter UI look and increase User Experience

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by awezmirza** [comment]
Please assign me this issue under hacktoberfest topic

**Comment by jeevan10017** [comment]
@awezmirza go ahead
