### ISSUE TITLE
Add Newsletter Subscription Feature Using Firebase

### ISSUE THREAD

**Issue by anuragbansall** [Open-Code-Crafters/FitFlex#118]
Hey @jeevan10017 ,

It looks like there’s no functionality for subscribing to the newsletter, so users are unable to subscribe and receive important updates. I’d like to add this feature using Firebase. Please assign this issue to me.

**Comment by jeevan10017** [comment]
> Hey @jeevan10017 ,
> 
> It looks like there’s no functionality for subscribing to the newsletter, so users are unable to subscribe and receive important updates. I’d like to add this feature using Firebase. Please assign this issue to me.
> 

@anuragbansall 
Go ahead

**Comment by anuragbansall** [comment]
Hi @jeevan10017 ,
I have raised a PR to address the issue regarding the newsletter subscription feature using Firebase. 
Please check it out at your convenience. Looking forward to your feedback!
