### ISSUE TITLE
Adding "Blog" Section.

### ISSUE THREAD

**Issue by SCR01** [Open-Code-Crafters/FitFlex#12]
The **"Start Exercise"** button appears to have a different style and alignment compared to the overall design of the site. This can affect the user experience and make the button less **visually appealing**.

**Suggested Solution:**

- Adjust the button to ensure it aligns with the design elements (margins, colors, font).
- Use a consistent button style for a more cohesive look.

![sdf](https://github.com/user-attachments/assets/4721ef88-881e-4cf8-887e-af9d66c38a88)

**Comment by manu-hn** [comment]
Hi, @jeevan10017 @SCR01, I would like to work on this issue and will modify the button style to provide an appealing UI experience.

**Comment by jeevan10017** [comment]
@manu-hn Thanks for your suggestion! However, changing the color or alignment of a single button isn't considered a substantial contribution to open source. I'd recommend finding more bugs or enhancements and combining them into one issue for a more meaningful contribution.

Looking forward to your input!

**Comment by SCR01** [comment]
@jeevan10017 I have a suggestion instead of doing this, we can add one more section in the nav bar related to the blog which can provide articles and blogs regarding fitness and exercise.

**Comment by jeevan10017** [comment]
@SCR01 Please confirm if you want to work on this enhancement, so I can assign it to you.

**Comment by SCR01** [comment]
@jeevan10017 I edited the title I will do the enhancement!

**Comment by jeevan10017** [comment]
@SCR01 Assigned..!. I may change the level based on your work during the pull request.

**Comment by SCR01** [comment]
@jeevan10017 Yeah, np.
