### ISSUE TITLE
[Feature Request]: Dockerize the Application

### ISSUE THREAD

**Issue by haseebzaki-07** [Open-Code-Crafters/FitFlex#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

### Use Case

Dockerfile leads to easy development and deployment process.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Sami3160 For now, are we required to Dockerize this application?

**Comment by Sami3160** [comment]
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues
> 
> ### Feature Description
> 
> I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
> Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.
> 
> ### Use Case
> 
> Dockerfile leads to easy development and deployment process.
> 
> ### Benefits
> 
> _No response_
> 
> ### Add ScreenShots
> 
> _No response_
> 
> ### Priority
> 
> High
> 
> ### Record
> 
> - [X] I have read the Contributing Guidelines
> - [X] I'm a GSSOC-EXT contributor
> - [X] I'm a HACKTOBERFEST contributor
> - [X] I have starred the repository

Tell in details how adding docker will affect our project, how we need to run the project and how will be the installation process... 
And how we maintain the docker container, also explain how it is scalable for our project 

I'm really interested in integrating docker, but don't know how it would affect our project,

**Comment by haseebzaki-07** [comment]
hey @Sami3160  and @jeevan10017  adding docker to a project is never early as it has always that thing to make the development process easier, It keeps away the dependencies that one needs to manually install to their system to get started with the project , instead it takes care all of that , it needs a single command to make a image of the application inside the docker container and another command will run the application on the specified ports.

Docker offers consistent, lightweight containers that simplify app deployment across environments, ensuring portability and isolation. It also enables easy scaling by allowing rapid container replication and resource allocation based on demand.

**Comment by Sami3160** [comment]
> hey @Sami3160  and @jeevan10017  adding docker to a project is never early as it has always that thing to make the development process easier, It keeps away the dependencies that one needs to manually install to their system to get started with the project , instead it takes care all of that , it needs a single command to make a image of the application inside the docker container and another command will run the application on the specified ports.
> 
> Docker offers consistent, lightweight containers that simplify app deployment across environments, ensuring portability and isolation. It also enables easy scaling by allowing rapid container replication and resource allocation based on demand.

Okay you can use docker but you need to update readme.md,
Have some detailed readme about how to run container and create images add dependency and every thing such that even a beginner can run our app and contribute to it without any problem

**Comment by haseebzaki-07** [comment]
Yeah sure I will update the Readme.md in the way that is understandable by everyone.
