### ISSUE TITLE
[Feature Request]: Add colored background

### ISSUE THREAD

**Issue by Mehtarishita** [Open-Code-Crafters/FitFlex#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can add subtle colors to make your website look more attractive and user-friendly.
Please assign this issue to me under gssoc'24 EXTENDED with the label gssoc'24 and hacktoberfest.

### Use Case

to uniquely identify keypoints

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a194b986-b835-405b-9fa0-d4207bba4229)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Mehtarishita, I may merge or not based on your colouring design in PR.
