### ISSUE TITLE
[Feature Request]: Add Calculators in services

### ISSUE THREAD

**Issue by pavitraag** [Open-Code-Crafters/FitFlex#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When creating a fitness-related application or tool, there are several calculators you can integrate to help users track their health, performance, and fitness goals. Here are some popular fitness calculators you might consider adding:

1. Body Mass Index (BMI) Calculator
Purpose: Helps users determine if they are underweight, normal weight, overweight, or obese based on their height and weight.
2. Basal Metabolic Rate (BMR) Calculator
Purpose: Estimates the number of calories a person needs to maintain their current weight at rest, which is useful for understanding daily caloric needs.
3. Caloric Needs Calculator
Purpose: Estimates the total daily caloric intake required to maintain or achieve specific fitness goals (e.g., weight loss, maintenance, or muscle gain).
4. Body Fat Percentage Calculator
Purpose: Estimates body fat percentage based on various measurements, which can help users track fat loss or muscle gain.

### Use Case

Integrating fitness calculators into a fitness-related application can significantly enhance user experience and engagement by providing personalized insights and actionable recommendations. For instance, the **Body Mass Index (BMI) Calculator** allows users to determine their weight category, serving as a foundation for setting realistic weight management goals, complemented by tailored content like workout plans for specific BMI categories. The **Basal Metabolic Rate (BMR) Calculator** helps users understand their calorie needs at rest, enabling informed dietary decisions, while the **Caloric Needs Calculator** allows users to estimate their daily caloric intake based on activity levels, facilitating effective weight management strategies. Lastly, the **Body Fat Percentage Calculator** helps users track their fat loss or muscle gain, offering valuable feedback that can motivate and guide their fitness journeys. Together, these features create a comprehensive tool that empowers users to monitor their health, customize their fitness plans, and achieve their goals more effectively.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
nice idea! @pavitraag go ahead

**Comment by coderKrysio** [comment]
Hey @jeevan10017,
is this issue still available to work for?
