### ISSUE TITLE
[Bug]: Footer Links do not redirect to the required locations.

### ISSUE THREAD

**Issue by Jay-1409** [Open-Code-Crafters/FitFlex#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="959" alt="image" src="https://github.com/user-attachments/assets/6053143a-9f5f-4eb2-b062-9d9b3ebd6a12">

The links in the footer do not redirect to the required locations.
For example the Health tips link should redirect to the health tips page, but it simply redirects to the home page.

### Expected behavior

The links should redirect the required locations

### Add ScreenShots

<img width="959" alt="image" src="https://github.com/user-attachments/assets/ccb9c9eb-8224-4769-b4c0-ccd1107d62d6">

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Jay-1409  Closing the issue due to it is not required
