### ISSUE TITLE
About Us Page Updation and Footer Logo Updation of Twitter to X

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#13]
I have noticed the footer section is not very attractive, user-friendly, and also the wrong logo (twitter logo) which is now X.

![image](https://github.com/user-attachments/assets/cbe5d6f9-b7fa-4cb1-8f13-4f25d91ce109)

Also I have noticed that the About us page is also not that much informative and well structured

![image](https://github.com/user-attachments/assets/3461608a-57c2-437a-9039-365bd42a7797)

@Kritika30032002 @Sami3160 @jeevan10017
please assign this task to me.

**Comment by jeevan10017** [comment]
@Shariq2003 go ahead

**Comment by Shariq2003** [comment]
I have done and also raise a PR.
@jeevan10017 sir please check
