### ISSUE TITLE
Add animation to Success Stories

### ISSUE THREAD

**Issue by AmanKumar1115** [Open-Code-Crafters/FitFlex#130]
**Contributor Information**
Please check if you are a contributor from:
- [✔️ ] GSSoC-ext
- [✔️ ] Hacktoberfest

I can add animation to success story cards for better Visual Appeal and Engagement.

**Comment by jeevan10017** [comment]
@AmanKumar1115, and also enhance the card design with the website colouring theme. give some spacing between cards

**Comment by AmanKumar1115** [comment]
> @AmanKumar1115, and also enhance the card design with the website colouring theme. give some spacing between cards

ok

**Comment by AmanKumar1115** [comment]
@jeevan10017  can please update the level here also

**Comment by jeevan10017** [comment]
@AmanKumar1115  this is just for estimation level, at last your  levels in PR were counted.
