### ISSUE TITLE
[Bug]: Infinite like glitch 

### ISSUE THREAD

**Issue by sriraghavi22** [Open-Code-Crafters/FitFlex#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

User can like the blog post multiple times without even logging in.

### Expected behavior

It can only be liked only once by a user and if he try to click it again then the like should be removed

### Add ScreenShots

https://github.com/user-attachments/assets/1359d8ab-fd62-4baf-bea0-dc1283c41ec2

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@sriraghavi22  go ahead. Possibe to add another feature If an unregistered user clicks the like button, then it should be transferred to the register pages.
