### ISSUE TITLE
[Feature Request]: Privacy Policy page to the website

### ISSUE THREAD

**Issue by govindumeesala** [Open-Code-Crafters/FitFlex#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Description: We need to add a Privacy Policy page to our bus and train ticket booking platform to ensure legal compliance and build user trust. This page will outline how we collect, use, store, and protect user data, as well as how users can manage their data and privacy settings.

Create a dedicated Privacy Policy page linked from the footer or main navigation.
The page should cover:
- What personal information is collected (e.g., name, email, payment info)
- How the data is used (e.g., for bookings, communications)
- Who it is shared with (e.g., third-party services like payment processors)
- User rights (e.g., data access, deletion requests)
- Cookie and tracking policies

### Use Case

Why this is important:

- User Trust: A clear privacy policy will increase transparency, allowing users to understand how their data is being handled, enhancing trust in the platform.
- Third-party Integrations: Many third-party services we may use (e.g., payment gateways, analytics) require a privacy policy.
- Consent Management: It will help manage user consent regarding cookies, email communication, and tracking.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@govindumeesala go ahead.
