### ISSUE TITLE
Persisting Dark mode preference across visits

### ISSUE THREAD

**Issue by anuragbansall** [Open-Code-Crafters/FitFlex#136]
Hi @jeevan10017 ,

I noticed that when users reload the site, their last dark mode preference isn't saved, and the site defaults back to light mode. I'd like to fix this so that when users revisit the site, their last selected theme is saved and applied automatically, preventing the need to change it every time.

I plan to implement this using either localStorage or cookies. Kindly assign this issue to me.

Thanks!

**Comment by jeevan10017** [comment]
@anuragbansall go ahead
