### ISSUE TITLE
[Feature Request]: Add rate us/feedback option

### ISSUE THREAD

**Issue by Aditijainnn** [Open-Code-Crafters/FitFlex#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

in the footer add feedback option for better user interaction

### Use Case

Assign this to me under gssoc ext and hacktoberfest

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Aditijainnn go ahead
