### ISSUE TITLE
[Feature Request]: Add card with hover

### ISSUE THREAD

**Issue by hritika2409** [Open-Code-Crafters/FitFlex#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

<img width="793" alt="image" src="https://github.com/user-attachments/assets/b2b8a8e3-9c34-4bcd-bf61-94226dfdcdc8">

### Use Case

Changing it to a interactive card so that it is more attractive and welcoming

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@hritika2409 it is not required by now.
