### ISSUE TITLE
Lacks Workout page

### ISSUE THREAD

**Issue by 1ShahidBashir** [Open-Code-Crafters/FitFlex#142]
The project is really good but being a fitness website I believe it should have a page that teaches you some basic workouts
![image](https://github.com/user-attachments/assets/61932998-cc28-441e-ad73-d2a7a822788a)
would love to work on this project

**Comment by 1ShahidBashir** [comment]
assign this issue to me we can create a page for it

**Comment by jeevan10017** [comment]
@1ShahidBashir update?

**Comment by GAVINESHWAR** [comment]
@1ShahidBashir , Still no updates
