### ISSUE TITLE
[Bug]: Login page and landing page

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [Open-Code-Crafters/FitFlex#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Login Page Not Found & Navigation Issue
The login page is not accessible directly, which is a critical issue. Currently, the login link is missing from the navigation menu, forcing users to navigate to the registration page first before they can access the login page. This is not a good user experience, as users should be able to access the login page directly from the navigation.

Landing Page and Navigation Overlap
The landing page content is mixed with the navigation bar, negatively impacting the user experience. The landing page information should be displayed separately, without overlapping with the navigation, to provide a clear and intuitive interface for users.

![image](https://github.com/user-attachments/assets/3f8c59c3-1212-4828-a30f-010db76cc9b4)
![image](https://github.com/user-attachments/assets/15c34b2a-025e-43ca-8d7f-1a197c5d44da)

### Expected behavior

Users should be able to access the login page directly from the navigation bar without needing to go through the registration page.
Upon logging in, users should be able to access the dashboard seamlessly.
The landing page content should be distinct from the navigation bar, ensuring a clean and intuitive user interface for a better overall user experience.

### Record

- [x] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Kuldeepsinghrajpoot go ahead
