### ISSUE TITLE
[Feature Request]: Add fitbot ( a personal trainer chatbot)

### ISSUE THREAD

**Issue by amanver45** [Open-Code-Crafters/FitFlex#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

FitBot is an innovative personal trainer chatbot designed to enhance your fitness journey on FitFlex. Acting as your virtual fitness coach, FitBot provides real-time guidance, motivation, and support tailored to your individual needs. Whether you're looking to lose weight, build muscle, or improve your overall fitness, FitBot offers personalized workout suggestions, nutritional advice, and progress tracking.

### Use Case

Customized Workouts: Get daily workout recommendations based on your goals and fitness level, ensuring you stay challenged and engaged.
Nutrition Guidance: Receive tailored meal plans and nutritional tips to complement your fitness routine and help you achieve your weight loss or muscle gain objectives.
Progress Tracking: Easily log your workouts, monitor your progress, and receive feedback to keep you motivated.
24/7 Support: FitBot is available around the clock to answer your questions, provide encouragement, and help you overcome any challenges you may face in your fitness journey.
Interactive Chat Experience: Engage in friendly, conversational interactions that make working out feel more enjoyable and less daunting.

### Benefits

With FitBot by your side, achieving your fitness goals becomes a fun and interactive experience. Let FitBot guide you, motivate you, and keep you accountable as you embark on your path to a healthier, fitter you!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@amanver45 Someone is working on that; I will let you know if further help is required to him.

**Comment by amanver45** [comment]
Can you mention issue that work on fitbot  because #37 is closed

**Comment by amanver45** [comment]
@jeevan10017 PLS REPLY

**Comment by amanver45** [comment]
@jeevan10017 he close the issue
