### ISSUE TITLE
Footer Section Can be improved

### ISSUE THREAD

**Issue by Sameeratweb** [Open-Code-Crafters/FitFlex#15]
Adding a more efficient and responsive footer section would be a good idea for navigation and better UI

i would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by jeevan10017** [comment]
@Sameeratweb It looks like someone else is already working on this. Please take a moment to check for other issues before adding a new one. Thank you!
