### ISSUE TITLE
Footer Design and Functionality Problems

### ISSUE THREAD

**Issue by Priyanshu282003** [Open-Code-Crafters/FitFlex#150]
Description: There are a few potential issues in the footer section of the website that need attention:

Language Selector Position: The language selector powered by Google Translate might be better aligned or placed in a different position for a more consistent and user-friendly layout.
Social Media Icons Styling: The social media icons (Facebook, Instagram, LinkedIn, etc.) might need better spacing or styling to align them with the design language of the website.
Subscribe Form: The "Subscribe" form and button look slightly detached from the rest of the footer. It might benefit from design adjustments to improve consistency with the footer layout and spacing.
Legal Links Alignment: The links like "Privacy Policy", "Terms of Use", etc., could be better aligned for a more polished look.
Suggested Changes:

Adjust the placement of the language selector for better balance.
Review the padding/margin of the social media icons for improved presentation.
Consider improving the spacing between the "Subscribe" form and other footer elements.
Align legal links properly to maintain uniformity across the footer.
Steps to Reproduce:

Visit the site.
Scroll down to the footer.
Observe the alignment and layout issues mentioned above.
Expected Behavior:

The footer should have consistent design elements with well-aligned components.
Screenshot:
![image](https://github.com/user-attachments/assets/b3c0ff0d-954c-4027-a1c7-98f8de75e56e)

**Comment by GAVINESHWAR** [comment]
@Priyanshu282003 , go ahead .
