### ISSUE TITLE
[Bug]: Light/Dark Toggle Theme not working as expected on Contact/Register Pages Buttons Click

### ISSUE THREAD

**Issue by rajgharat07** [Open-Code-Crafters/FitFlex#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bug Description:

- Issue: The light/dark theme toggle functionality is not working as expected on the "Contact" and "Register" pages, specifically affecting button styling. When the theme toggle is clicked, the button colors and styles do not update accordingly to reflect the selected light or dark mode.

- Expected Behavior: The buttons on the "Contact" and "Register" pages should dynamically switch their styles between light and dark modes when the theme toggle is clicked. For instance, the button background and text color should adjust based on the selected mode, ensuring a consistent user interface across all pages.

- Impact: Users experience inconsistent theme behavior, where buttons remain in the default style even after toggling between light and dark themes. This can lead to confusion and affect the overall user experience.

- Steps to Reproduce:

  - Navigate to the "Contact" or "Register" page.
  - Click on the light/dark toggle button.
  - Observe that the buttons do not change their styles to match the selected theme.

### Expected behavior

When the light/dark theme toggle is clicked on the "Contact" and "Register" pages, the entire page, including the buttons, should immediately update to reflect the selected theme. Specifically:

- Light Mode:

  - Buttons should have a light background color with dark text.
Hover and active states should complement the light mode with subtle color changes.

- Dark Mode:

  - Buttons should have a dark background color with light text.
Hover and active states should complement the dark mode with darker or more muted hover effects.
The styling should remain consistent across the entire page to provide a cohesive and visually clear experience for the user.

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@rajgharat07 go ahead

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd
