### ISSUE TITLE
[Feature Request]: Sliders in home 

### ISSUE THREAD

**Issue by isimarjitsingh** [Open-Code-Crafters/FitFlex#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i would like to enhance your  both image sliders of home page , i able to put good carousel effect and also try to give some good CSS to your "success stories" carousel, stack stacks i gonna used:-CSS, Reactjs

### Use Case

it will provide left right swipe in "success stories " carousel , and by enhancing css in both carousel your home page gonna be looks like proficient one's

### Benefits

It helps to provide user friendly webpage ,because always a homepage decide decorum of whole website

### Add ScreenShots

![Screenshot 2024-10-10 232539](https://github.com/user-attachments/assets/e6654107-b3b2-4d62-849b-bcfedc75e4d4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@isimarjitsingh just merged!
