### ISSUE TITLE
[Feature Request]: Addition of Scrolling Progress Bar Like GSSOC Website Should be in the Fitlex Website for Better UI and UX

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Scrolling Progress Bar Like GSSOC Website Should be in the Fitlex Website for Better UI and UX

### Use Case

.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9797a411-e182-47c1-859b-328719903b49)

Look at the top (Orange Progress Bar)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Shariq2003 👍

**Comment by Shariq2003** [comment]
@jeevan10017 sir, This feature should be of level 2, I am also adding the same in recodehive by sanjay sir, the issue is of level 2 there too.
please increase if u agree.

**Comment by jeevan10017** [comment]
> @jeevan10017 sir, This feature should be of level 2, I am also adding the same in recodehive by sanjay sir, the issue is of level 2 there too.
> please increase if u agree.

Remind @ PR

**Comment by Shariq2003** [comment]
> > @jeevan10017 sir, This feature should be of level 2, I am also adding the same in recodehive by sanjay sir, the issue is of level 2 there too.
> > please increase if u agree.
> 
> Remind @ PR

okay @jeevan10017 sir 😊

**Comment by Shariq2003** [comment]
> > @jeevan10017 sir, This feature should be of level 2, I am also adding the same in recodehive by sanjay sir, the issue is of level 2 there too.
> > please increase if u agree.
> 
> Remind @ PR I think, it doesn't reflect your leaderboard

I didn't understand sir, what u are trying to say.
