### ISSUE TITLE
Customisation Of Loading Screen Should | Screen Should not be White/Blank with Loader

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#159]
The Loading Screen should not be white in the background with loader, it is not looking good.
It should be somewhat of transparent or website theme matched.

https://github.com/user-attachments/assets/77646288-2236-4663-b08d-2444dbae04a6

**Contributor Information**
Please check if you are a contributor from:
- [X] GSSoC-ext
- [X] Hacktoberfest

**Comment by jeevan10017** [comment]
@Shariq2003 👍
