### ISSUE TITLE
it looks like something is obscuring part of the screen

### ISSUE THREAD

**Issue by Sameeratweb** [Open-Code-Crafters/FitFlex#16]
![Screenshot 2024-10-02 065733](https://github.com/user-attachments/assets/a0930747-07eb-49a1-a40a-59edca0b9150)
![Screenshot 2024-10-02 065944](https://github.com/user-attachments/assets/4864754c-5531-4b62-acf1-677ce3b37677)
user might get confused whether to scroll or it is an slideshow feature , the button disappears upon hovering . 

i would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by jeevan10017** [comment]
@Sameeratweb, go ahead
