### ISSUE TITLE
Addition of Persistent Storage for UserData | ChatBot Enhancement | Optimisation of Recurrence Of Questioning

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#165]
I want to add the Persistent Storage for the optimisation of UserData Flow for ChatBot Flow.
In this, I am going to implement the sessionStorage / localStorage for the userData storing that results in optimization of ChatBot Flow.

**Contributor Information**
Please check if you are a contributor from:
- [X] GSSoC-ext
- [X] Hacktoberfest

**Comment by jeevan10017** [comment]
@Shariq2003
