### ISSUE TITLE
Improve footer section

### ISSUE THREAD

**Issue by Son7c** [Open-Code-Crafters/FitFlex#166]
**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

![Screenshot 2024-10-11 145336](https://github.com/user-attachments/assets/c75a07fb-249b-487c-a0c9-c9c91be3c93e)

The footer section can be improved please assign this to me.

**Comment by GAVINESHWAR** [comment]
@Son7c , could you say more about the improvement?

**Comment by Son7c** [comment]
@GAVINESHWAR The social icons are too large and are taking too much space that can be fixed.

The copyright section can be placed at extreme end.

The extra subscribe option above email input can be removed.

Select language can be placed below email input aream

**Comment by Son7c** [comment]
@GAVINESHWAR The social icons are too large and are taking too much space that can be fixed.

The copyright section can be placed at extreme end.

The extra subscribe option above email input can be removed.

Select language can be placed below email input aream

**Comment by GAVINESHWAR** [comment]
@Son7c, Go for it .

**Comment by Son7c** [comment]
@GAVINESHWAR Can you please mention level2 because i had to learn react to implement the changes.

**Comment by GAVINESHWAR** [comment]
@Son7c , for the design update level 1 will be given please go through it, if your contribution is impressive then I will change don't worry.

please continue with your contribution

**Comment by Son7c** [comment]
@GAVINESHWAR check my PR

**Comment by GAVINESHWAR** [comment]
Jeevan will merge your PR after review 

Thank you
