### ISSUE TITLE
[Bug]: Footer links don't work.

### ISSUE THREAD

**Issue by Jay-1409** [Open-Code-Crafters/FitFlex#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer links do not redirect to the prospective pages.

### Expected behavior

They should redirect to the existing pages such as health tips.

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Jay-1409, not required now #168 closed as complete.
