### ISSUE TITLE
Add a Loading Page Instead of Simple Div for Fallback in Suspense

### ISSUE THREAD

**Issue by MihirSaiDudekula** [Open-Code-Crafters/FitFlex#17]
**Is your feature request related to a problem? Please describe.**  
Currently, when components are being lazy-loaded in the application, the fallback UI is a simple `<div>Loading...</div>`. This does not provide a visually engaging experience or any indication of what is being loaded.

**Describe the solution you'd like**  
I propose creating a dedicated loading component that provides a more visually appealing loading state. This could include a spinner, animation, or any other design element that enhances the user experience during the loading process.

**Describe alternatives you've considered**  
One alternative is to use a third-party loading spinner library, but it may not align with the current design aesthetic of the application. Another option is to use a simple text message, but that lacks engagement.

**Contributor Information**  
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

**Comment by jeevan10017** [comment]
@MihirSaiDudekula go ahead👍

**Comment by MihirSaiDudekula** [comment]
I have made the following changes:

added a spinner for page loading:
![image](https://github.com/user-attachments/assets/617f0fb7-ce22-41fc-9f4e-de834939d229)

and a 404 not found page
![image](https://github.com/user-attachments/assets/0b0da5e1-8a87-4720-b7ef-19d671b38783)

can i proceed with PR @jeevan10017 ?

**Comment by MihirSaiDudekula** [comment]
please add the 'hacktoberfest' label instead of 'hactoberfest' (missing k)

**Comment by jeevan10017** [comment]
@MihirSaiDudekula Can you create an attractive loading spinner that matches the theme and content? or else create this as PR.

**Comment by MihirSaiDudekula** [comment]
> @MihirSaiDudekula Can you create an attractive loading spinner that matches the theme and content? or else create this as PR.

Got it, I'll try a bit and get back to you 

Any suggestions from your side?
How can I make it better?

**Comment by MihirSaiDudekula** [comment]
fixed the color scheme
![image](https://github.com/user-attachments/assets/067ffe47-d967-4816-979f-b1767a5874c6)
![image](https://github.com/user-attachments/assets/1319aa9f-ffe1-4467-9804-df7a7713ff79)

**Comment by MihirSaiDudekula** [comment]
Thanks. 

1 last request, kindly add 'hacktoberfest' label to the repository and 'hacktoberfest-accepted' label to this PR. since, it doesnt accept it otherwise.

![image](https://github.com/user-attachments/assets/b2c5c853-ecc1-4c5e-85ec-5a32904b1c86)

**Comment by jeevan10017** [comment]
@MihirSaiDudekula Thank you for the correction.😊👍
let me know if any other issues

**Comment by MihirSaiDudekula** [comment]
> @MihirSaiDudekula Thank you for the correction.😊👍 let me know if any other issues

Thanks a lot for the quick response! No such issues!
