### ISSUE TITLE
Implement Like Button Toggle Feature in Blog Component

### ISSUE THREAD

**Issue by harshucoder** [Open-Code-Crafters/FitFlex#175]
The Blog component currently allows users to click the "Like" button to increment the like count for each blog post. However, there is no toggle functionality implemented, which means that users can only increment the count and cannot un-like a post.

**Current Behavior:**

When a user clicks the "Like" button, the like count increases by one, regardless of whether they have previously liked the post.
There is no mechanism to decrement the count or toggle the like status.
Expected Behavior:

Implement functionality that allows users to:
Increment the like count when the button is clicked if the post has not been liked yet.
Decrement the like count when the button is clicked again if the post has already been liked.

https://github.com/user-attachments/assets/e0ade812-f36e-4646-ad64-c7d9b4328d62

**Proposed Solution:**

Introduce a state to track whether a post has been liked (boolean value).
Modify the handleLike function to toggle the like status:
Increment the like count if not liked.
Decrement the like count if already liked.
Update the UI accordingly to reflect the current like status.
Steps to Reproduce:

Open the blog page.
Click on the "Like" button for any blog post.
Observe that the like count increments but does not allow un-liking.

This issue is part of the GSSoC-Ext and Hacktoberfest labels, and solving this feature will enhance user interaction with the blog posts.

 Could you please assign this issue to me? I am eager to work on it and contribute to the project.
Contributor Information Please check if you are a contributor from:

 GSSoC-ext
 Hacktoberfest

**Comment by GAVINESHWAR** [comment]
@harshucoder , can the likes you give be viewed by other people as well?

**Comment by harshucoder** [comment]
@GAVINESHWAR Currently, the likes that users give to posts are stored only in local state. This means that when a user likes a post, the updated like count is only reflected in their view until the page is refreshed. Other users cannot see the changes in real time.

**Comment by harshucoder** [comment]
@GAVINESHWAR Sir Please do merge the pr
