### ISSUE TITLE
Login Page Improvement Request

### ISSUE THREAD

**Issue by samriddhitiwary** [Open-Code-Crafters/FitFlex#18]
**Is your feature request related to a problem? Please describe.**
The login page is not working properly. It does not authenticate users correctly, fails to redirect after login, and lacks proper form validation for incorrect inputs.
![image](https://github.com/user-attachments/assets/0fdd6f6f-f36a-455c-9e6f-af3a4c806f36)

**Describe the solution you'd like**
I want the login page to validate inputs before submission, show error messages for failed login attempts, and redirect to the main page upon successful login. I would also like to integrate a backend authentication system using Node.js and MongoDB for secure login.

**Describe alternatives you've considered**
I have considered implementing third-party authentication services like Firebase or Auth0 but would prefer building the authentication from scratch using a custom backend to better align with my project goals.

**Additional context**
The login page should include a "Remember Me" option and better UI responsiveness. Adding accessibility features like keyboard navigation would also improve the user experience.

**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext-YES
- [x] Hacktoberfest-YES

**Comment by samriddhitiwary** [comment]
@jeevan10017 Could please assign this issue to me under the label of GSSoC-ext and Hacktoberfest.

**Comment by jeevan10017** [comment]
@samriddhitiwary Integrate it with Firebase, and also with Google authentication feature.

**Comment by samriddhitiwary** [comment]
Thank you @jeevan10017  I will start working on it

**Comment by samriddhitiwary** [comment]
@jeevan10017 is there any deadline for this submission?

**Comment by jeevan10017** [comment]
> @jeevan10017 is there any deadline for this submission?

No deadline, but finish ASAP.

**Comment by samriddhitiwary** [comment]
@jeevan10017 yes I'm working on it

**Comment by jeevan10017** [comment]
@samriddhitiwary are you working on it?

**Comment by samriddhitiwary** [comment]
@jeevan10017 Yes I'm working on it, please give me 1-2 days more

**Comment by samriddhitiwary** [comment]
> @samriddhitiwary are you working on it?

Yes I am

**Comment by samriddhitiwary** [comment]
@jeevan10017 Have you created the Firebase API?

**Comment by jeevan10017** [comment]
Create it with your own API. We will be changing it later.
Have you worked with creating a firebase earlier?

**Comment by samriddhitiwary** [comment]
@jeevan10017 I had done it once while learning ReactJs where they did have a section for Firebase.
Though college commitments have kept me from dedicating my full time, I’m confident that I’ll be able to complete it within 2-3 days.

**Comment by jeevan10017** [comment]
@samriddhitiwary other people want to contribute to this creating firebase integration who was experienced. If you want any help, I will assign him in this issue. So you both can work on this.

**Comment by samriddhitiwary** [comment]
@jeevan10017 I'm confident that I will be able to complete it please just give me time till Monday, if I am not able to do it by then you please do assign the other person also and then we will surely work together.

**Comment by jeevan10017** [comment]
> @jeevan10017 I'm confident that I will be able to complete it please just give me time till Monday, if I am not able to do it by then you please do assign the other person also and then we will surely work together.

Ok go ahead, possible to complete ASAP.

**Comment by samriddhitiwary** [comment]
@jeevan10017 Thank you

**Comment by samriddhitiwary** [comment]
@jeevan10017 I have implemented the Google Authorization, do I have to also implement the Email and password Authentication?

**Comment by jeevan10017** [comment]
@samriddhitiwary also work on intake of registration credentials and validation of email/ph no with password in while login login.

**Comment by samriddhitiwary** [comment]
@jeevan10017 Can I just Merge the Google Authorization right now and raise separate issue for this.

**Comment by samriddhitiwary** [comment]
@jeevan10017 I the Google Authorization is working correctly and the Log In and the Sign-In are working correctly.
I can surely implement the email and the number  Authorization it would be really good if we can raise a separate issue and work on it.

**Comment by jeevan10017** [comment]
@samriddhitiwary carry on..

**Comment by samriddhitiwary** [comment]
@jeevan10017 I'm sorry I did'nt get you

**Comment by jeevan10017** [comment]
Initiate PR. And create new issue.

**Comment by samriddhitiwary** [comment]
@jeevan10017 Thank you

**Comment by samriddhitiwary** [comment]
@jeevan10017 I have raised PR please review it the link is below
https://github.com/Open-Code-Crafters/FitFlex/pull/56
If they meet your requirements then could you please also add the labels in PR/MR too

**Comment by samriddhitiwary** [comment]
@jeevan10017 ??

**Comment by samriddhitiwary** [comment]
@jeevan10017 There was a conflict with my package-lock-json, that's why I took the latest pull today but I a, getting these errors, though the code running is properly in my local machine
![image](https://github.com/user-attachments/assets/4364bfab-f2c9-4b03-8a8f-d611f822fd86)
