### ISSUE TITLE
[Feature Request]: Services Page Enhancement | Redesigning

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Services page is not according to the website theme, the container looks weird.

### Use Case

.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fdca9065-cfbb-491a-9808-ecf33fcec813)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
#182
