### ISSUE TITLE
Enhancemet of Navbar | Service Page Redesigning | Contact Us Page Theme Issue | Name Field Occur Twice in Service Scheduling

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#182]
![image](https://github.com/user-attachments/assets/ae76cc5c-f8a8-4668-8410-fddbd0265e68)

![image](https://github.com/user-attachments/assets/05290bf3-5c5e-4a54-bce8-7bbe4bda62cf)

![image](https://github.com/user-attachments/assets/14c67472-d99f-44e1-8988-f79728ffd4e8)

![image](https://github.com/user-attachments/assets/aad0b15e-6fc2-480f-9496-e89a66ecdda5)

### All Tasks : 
1. Dark Mode/Light Mode not working in Contact Us Page
2. Services Page Enhancement | Redesigning
3. Name Field Occur Twice in Service Scheduling
4. Addition of Hover Effect on Navbar

**Contributor Information**
Please check if you are a contributor from:
- [X] GSSoC-ext
- [X] Hacktoberfest

**Comment by jeevan10017** [comment]
@Shariq2003 go for it.
And also change the font style matches with the website.
May use glass effect.

**Comment by jeevan10017** [comment]
Make all these in one

**Comment by Shariq2003** [comment]
okay

**Comment by Shariq2003** [comment]
@jeevan10017 please review and merge my PR.

**Comment by Shariq2003** [comment]
@jeevan10017 also please take a look at issue #233 for the level

**Comment by jeevan10017** [comment]
> @jeevan10017 also please take a look at issue #233 for the level

I will see about it while merging.

**Comment by Shariq2003** [comment]
@jeevan10017 i have completed all the above-mentioned task in my PR #232, and I have added level 2.
please increase the level to 3 as you have also assigned me all the tasks that are the combined by the issues #179 #180 #181

**Comment by Shariq2003** [comment]
@jeevan10017 sir ?

**Comment by Shariq2003** [comment]
> > @jeevan10017 also please take a look at issue #233 for the level
> 
> I will see about it while merging.

@jeevan10017 sir,
