### ISSUE TITLE
[Bug]: Contact us two name boxes

### ISSUE THREAD

**Issue by haseebzaki-07** [Open-Code-Crafters/FitFlex#184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is two fields same for filling name on the schedule a  session section under services when booking an appointment.

### Expected behavior

It should have only one name field and any other field if required.

### Add ScreenShots

![Screenshot 2024-10-11 234545](https://github.com/user-attachments/assets/4d0db225-b483-482f-88bb-2bdbf4e14d3f)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
Already assigned to someone
