### ISSUE TITLE
Footer section in small screen needs redesigning 

### ISSUE THREAD

**Issue by YooAshu** [Open-Code-Crafters/FitFlex#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer section looks like a vertical line of texts 
And 
If you check the screenshot you can see that the last social button can't even be clicked 

### Expected behavior

Footer should not take full screen height and last link should be visible 

### Add ScreenShots

![Screenshot_20241012_013545](https://github.com/user-attachments/assets/ac54fd1f-730f-40e4-996c-53af4547b03a)

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@YooAshu , go a head
