### ISSUE TITLE
[Bug]: Overlapping Issue Register Form and Footer; Login Button Redirects to Non-Existent Route

### ISSUE THREAD

**Issue by Konain-Raza** [Open-Code-Crafters/FitFlex#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The application currently has a login button that redirects users to a route that does not exist, leading to confusion and a poor user experience. Additionally, the Google Authentication is implemented using a popup, which disrupts the user experience and may not work well for all users.

Instead of routing to a non-existent page, the login functionality should be handled through conditional rendering. This approach would allow users to toggle between the sign-in and registration forms on the same page, enhancing usability and streamlining the authentication process.

### Expected behavior

The application should utilize conditional rendering to display either the sign-in or registration form based on user interaction, instead of redirecting to a nonexistent route.
The Google Authentication process should be integrated into the same component, allowing for a smoother transition and user experience without the need for popups.

### Add ScreenShots

![Screenshot from 2024-10-12 11-06-34](https://github.com/user-attachments/assets/a552ca98-3fc5-4491-8c7f-8f5628d55ec4)
![Screenshot from 2024-10-12 11-06-53](https://github.com/user-attachments/assets/69826a48-1f95-400a-8458-beaed48890bb)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Konain-Raza , Go ahead
