### ISSUE TITLE
[Bug]: Responsive 

### ISSUE THREAD

**Issue by Kuldeepsinghrajpoot** [Open-Code-Crafters/FitFlex#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"I will resolve the issues by redesigning the interface to be responsive. I'll use Shadcn components along with Tailwind CSS for a better, lightweight, and fully responsive UI across phone and tablet screens."

This way, you ensure flexibility and efficiency for various screen sizes while maintaining a modern and minimal design.

![image](https://github.com/user-attachments/assets/a7dfe5fb-884f-406f-a78e-86aee39eff65)
![image](https://github.com/user-attachments/assets/8fec7d69-109b-4e1c-a92f-ffe2b6261398)

### Expected behavior

**Expected Behavior:**

The UI should automatically adjust and display properly on both phone and tablet screens, ensuring that all elements are easily readable and accessible without any layout distortion. The design should be fully responsive, with proper alignment, spacing, and scaling of content based on screen size, providing a seamless and user-friendly experience on mobile devices.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Kuldeepsinghrajpoot, start your contribution to the project I hope You make the proper responsive to the website please add the screenshots at the time of Pr submission.

**Comment by GAVINESHWAR** [comment]
@Kuldeepsinghrajpoot, Are you talking about Bootstrap

**Comment by Kuldeepsinghrajpoot** [comment]
I talk about tailwind CSS and shadcn UI

**Comment by GAVINESHWAR** [comment]
Ok go for it @Kuldeepsinghrajpoot.

**Comment by Kuldeepsinghrajpoot** [comment]
thank you so much
