### ISSUE TITLE
[Bug]: Footer section links are not attached

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [Open-Code-Crafters/FitFlex#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Even though the section and pages exist , the items in footer section are not attached with their respective links

pls. assign this issue to me , I'd love to work on it

### Expected behavior

Like the contact us page exist , but when you click the contact in footer section it does nothing , same goes for about us , faqs , and every other item that should have working link in footer.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@
