### ISSUE TITLE
[Feature Request]: Clicking on logo should redirect to home page

### ISSUE THREAD

**Issue by jvkousthub** [Open-Code-Crafters/FitFlex#195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Where ever the user is when user clicks on logo it should go to home page

### Use Case

easy navigation

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by itznayan** [comment]
please assign this issue to me.

**Comment by jvkousthub** [comment]
I am ready to work on it

**Comment by GAVINESHWAR** [comment]
@jvkousthub ,  #195 closed as completed
