### ISSUE TITLE
[Feature Request]: Add effect to faq question upon hover

### ISSUE THREAD

**Issue by jvkousthub** [Open-Code-Crafters/FitFlex#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A hover effect can be added to faq question to make it look more appealing

### Use Case

good looking

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@jvkousthu, please add the reference screenshots.

Thank you
