### ISSUE TITLE
[Bug]: the send message text is not aligned to center

### ISSUE THREAD

**Issue by laxmikandivalasa** [Open-Code-Crafters/FitFlex#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (274)](https://github.com/user-attachments/assets/070e42ea-1af7-4db5-8be2-2b5f808bfb11)
the send message in yellow box is not aligned to center

### Expected behavior

it must be aligned to center to have users positive review

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@laxmikandivalasa, This is a good issue but, we can't assign for small issues please see more bugs and raise an issue again.

Thank you
