### ISSUE TITLE
[Feature Request]: Add Contributors Page to Display Project Contributors in the Website

### ISSUE THREAD

**Issue by pani2004** [Open-Code-Crafters/FitFlex#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The contributors page will display the details of the contributors who have contributed to this project.

### Use Case

Since this repo is part of a open source program it would be great to have a contributors page

### Add ScreenShots

 Ex  of my previous work - 

https://github.com/user-attachments/assets/f54edaa6-ecf7-4260-8fd3-f666af1f4497

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by pani2004** [comment]
@jeevan10017 @GAVINESHWAR Can I work on this?

**Comment by GAVINESHWAR** [comment]
@pani2004, not required now please go for another issue
