### ISSUE TITLE
[Feature Request]: F&Q PAGE 

### ISSUE THREAD

**Issue by isimarjitsingh** [Open-Code-Crafters/FitFlex#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

As i observe there is no F&Q  page which deals with the question  queries of user, you just merged Q&A section  in the home page 
and there is also a limited questions and user also don't have any way to put a question ,please assign me  this  work, it helps to build my core strong and it also helps to make a good interactive website 

### Use Case

it will provide a new whole page for questions which helps user to find their their answers and if there is no frequent question present in page  user raise a question by it self .

### Benefits

-user ask a questions?
-it gives a professional touch to website
-helps users to find solution fast

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@isimarjitsingh, add some reference images to assign the issues.
