### ISSUE TITLE
[Bug]: None of the footer , social media as well as other links work .

### ISSUE THREAD

**Issue by mahirabidi12** [Open-Code-Crafters/FitFlex#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

None of the footer , social media links work . It creates an unprofessional impression . Please assign me this issue so that i can make required changes along with some css optimisations. Also please add the hacktoberfest tag to the issue . I will try to make the changes as soon as possible .

### Expected behavior

I expect all the anchor tag to works . 

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@mahirabidi12, this update is not required now.

Thank you
