### ISSUE TITLE
[Documentation Update]: Add code of conduct file

### ISSUE THREAD

**Issue by INam1995** [Open-Code-Crafters/FitFlex#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

"I would like to create a comprehensive Code of Conduct file for this project that outlines our expectations for community behavior, defines unacceptable conduct, and provides clear guidelines for reporting violations. 

### Suggested Change

The file should include:

A commitment to inclusivity, respect, and welcoming behavior.
A detailed list of expected behaviors and examples of unacceptable actions.
Clear instructions on how to report violations, including contact information.
An explanation of the consequences for violating the Code of Conduct.
A scope that applies to all interactions within the project, both online and offline.
A statement of confidentiality for reports and the response timeline.
A reference or acknowledgment to a known Code of Conduct template, like the Contributor Covenant.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@INam1995,  this feature is not required now, please go for other contributions.

Thank you
