### ISSUE TITLE
[Feature Request]: add missing sign in modal

### ISSUE THREAD

**Issue by ananyag309** [Open-Code-Crafters/FitFlex#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When we click on sign it, it shows page not found. Fix that

### Use Case

Sign in page should take username and password 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@ananyag309, please provide the detail information how you resolve the issue.

Thank you
