### ISSUE TITLE
[Feature Request]: Add share option to blog with advance feature 

### ISSUE THREAD

**Issue by ananyag309** [Open-Code-Crafters/FitFlex#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

With like and comment, we can add share option to the blog, non sign in user can't read the whole blog 

### Use Case

Non user will be taken to register page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@ananyag309 , this feature is not required now.

Thank you
