### ISSUE TITLE
Text Readability and Styling Issues on FitFlex Page

### ISSUE THREAD

**Issue by TornovDutta** [Open-Code-Crafters/FitFlex#208]
# Issue: 
The text on the FitFlex webpage is not user-friendly due to the following reasons:
<ol>
<li>The font style and size make the content difficult to read, especially on different devices or screen sizes.
<li>The text lacks proper contrast with the background, reducing readability.
<li>The alignment and spacing between text blocks are inconsistent, leading to a cluttered appearance.
<li>Buttons ("Schedule a Session," "Get Started," and "Join Now") have inconsistent designs, and the text within them is not prominent enough for easy interaction.
</ol>
# Expected Solution: 
Improve the font style and size for readability, adjust text contrast, and ensure consistent alignment and button design to enhance the user experience.

### sceenshot:
![Screenshot 2024-10-13 115929](https://github.com/user-attachments/assets/9575adea-141c-4597-ae29-702cb2834001)

**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

**Comment by TornovDutta** [comment]
@jeevan10017 please assign this issuse to me and label the issuse

**Comment by GAVINESHWAR** [comment]
@TornovDutta , Some are working on it after reviewing it, we will assign you
