### ISSUE TITLE
Contact Us Page Validation Checks in Email

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#21]
The validation checks are missing in Contact Us Page.

Email validation is not there. 
![image](https://github.com/user-attachments/assets/345fbc9b-9efb-4e50-95ed-be4dc94de335)

Also the Styling in contact us page is not good at all.
On hovering, the scaling and grading changing makes the Form so weard,

**Contributor Information**
Please check if you are a contributor from:
- [X] GSSoC-ext
- [ ] Hacktoberfest

**Comment by jeevan10017** [comment]
@Shariq2003 go ahead. "I will assess your performance and assign a label to your score based on your work in the pull request.

**Comment by Shariq2003** [comment]
okay sir,
