### ISSUE TITLE
[Bug]: Incorrect google logo

### ISSUE THREAD

**Issue by PavanTeja2005** [Open-Code-Crafters/FitFlex#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The google logo in the signup page is incorrect.

![image](https://github.com/user-attachments/assets/3732f776-32bf-452b-b923-453fb38bfe76)

### Expected behavior

The logo should be straight and well displayed

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@PavanTeja2005, this is a tiny issue I can't assign you for simple things.
