### ISSUE TITLE
[Bug]: Add Avatar to FitFlex Customer Support Interface

### ISSUE THREAD

**Issue by akshadgujarkar** [Open-Code-Crafters/FitFlex#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a missing or malfunctioning avatar in the FitFlex customer support chatbot interface. This bug affects the visual appearance and usability of the interface, where the avatar, meant to represent the customer support AI, is either not displayed or incorrectly positioned.

### Expected behavior

1) The avatar should be visible next to each chatbot message.
2) The avatar should be properly aligned with the text and not interfere with the chat interface's layout.

### Add ScreenShots
   
![Screenshot 2024-10-14 134849](https://github.com/user-attachments/assets/85b12d3b-8354-49d5-b752-34d113056a40)

### On which device are you experiencing this bug?

 On all devices and browsers. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by akshadgujarkar** [comment]
could u pls assign this issue to me I am really wanna work on it

**Comment by GAVINESHWAR** [comment]
@akshadgujarkar, please go ahead and try to finish the issue as soon as possible.

Thank you

**Comment by sank8-2** [comment]
Can I also try fixing this

**Comment by GAVINESHWAR** [comment]
> Can I also try fixing this

@sank8-2, try to raise an new issue

**Comment by sank8-2** [comment]
I have already raised an issue, please assign it there

**Comment by akshadgujarkar** [comment]
@GAVINESHWAR sir  its Done , kindly reveiw the PR

**Comment by GAVINESHWAR** [comment]
Project admin will review your Pr don't worry

**Comment by akshadgujarkar** [comment]
@GAVINESHWAR  okay , thank you
