### ISSUE TITLE
[Bug]: Images not loading in the plans page

### ISSUE THREAD

**Issue by sank8-2** [Open-Code-Crafters/FitFlex#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The images for the plans that are fetched internally do not load.

### Expected behavior

The images should load without any problem, internal images not loading to WebPack

### Add ScreenShots

![image](https://github.com/user-attachments/assets/71734457-c0f6-495a-8e31-c0f6abdaa00c)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [x] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by sank8-2** [comment]
Assign this issue to me, please

**Comment by GAVINESHWAR** [comment]
@sank8-2 , please go ahead try to finish as soon as possible and add the images of changes you done.

**Comment by sank8-2** [comment]
Ok, sure

**Comment by sank8-2** [comment]
Hi, I have raised a PR for it.

**Comment by GAVINESHWAR** [comment]
Don't worry project admin will review your Pr
