### ISSUE TITLE
[Feature Request]: I want to add scroll reveal functionality 

### ISSUE THREAD

**Issue by aditya07389** [Open-Code-Crafters/FitFlex#226]
hello sir ,
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

When you scroll the images or text with fade and appear , this will give a aesthetic touch to the website 

checkout this website for ex of scroll reveal : https://www.nmit.ac.in/

### Use Case

It will make the website visually appealing 

### Add ScreenShots

https://www.nmit.ac.in/

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@ aditya07389, please go ahead and finish as soon as possible but these transitions and animations take more code to be changed.

**Comment by aditya07389** [comment]
I'll try to raise pr by tomorrow
