### ISSUE TITLE
[Feature Request]:  Add "Forget Password" Option to Login Page

### ISSUE THREAD

**Issue by MuhammadAshraf23** [Open-Code-Crafters/FitFlex#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description: 
Implement a "Forget Password" link on the login page to allow users to reset their password in case they forget it. When a user clicks the "Forget Password" button, an email with a password reset link is sent to their registered Gmail account. The user can click the link to navigate to a page where they are prompted to enter a new password, which will be used to change their current password.

### Use Case

Users may sometimes forget their password and get locked out of their accounts. By having a "Forget Password" option, users can easily reset their password and regain access to their accounts without needing to contact support. This improves user experience and minimizes frustration during login attempts.

### Benefits

**Improved User Experience**: Users will have a streamlined way to recover their accounts, making the login process more user-friendly and reducing frustration.
**Reduced Support Requests:** By enabling self-service password recovery, the number of support requests related to password issues will decrease, freeing up resources for other tasks.
**Enhanced Security:** Providing a secure password reset process helps ensure that users' accounts remain protected, as it eliminates the need for less secure workaround methods.
**Increased User Retention:** Users who have forgotten their passwords can still access the platform without creating a new account, thereby maintaining user retention.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@MuhammadAshraf23, not required now #229 closed as complete.
