### ISSUE TITLE
[Feature Request]: Redesigning of Blog Page

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/0dea5993-0a26-42a7-8bd3-983e3a90020b)

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Shariq2003, show some sample templates or photos so that, I shall assign you the issue.

**Comment by Shariq2003** [comment]
![image](https://github.com/user-attachments/assets/9630f29d-2e46-42a7-a349-f282b762adb6)

Kind of this,

I mean i will redesign the whole page, because the current version is too much weird and looks not good according to website

**Comment by GAVINESHWAR** [comment]
Ok @Shariq2003, please proceed.

**Comment by Shariq2003** [comment]
Hey @GAVINESHWAR could u please increase the level
