### ISSUE TITLE
The Register Form not coded properly

### ISSUE THREAD

**Issue by samar12-rad** [Open-Code-Crafters/FitFlex#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current Register.jsx, doesnt create the user. 
It just stores the emailId of the user currently. 
![image](https://github.com/user-attachments/assets/967b93e8-8f04-455b-8bdc-797602a6df46)

### Use Case

The Register form only handles email right now, All the other details on the page are useless if not implemented.
I will redesign the form so that the user successfully registers with all the data.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/fd97c9a0-f404-482a-8629-ba036b4568f4)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@samar12-rad , not required closed as complete

**Comment by samar12-rad** [comment]
@GAVINESHWAR , I am currently creating profile page, but for that, someinfo is needed which is entered in the form but not sent to the database .

**Comment by samar12-rad** [comment]
I currently have an issue assigned to create profile page which will show details of user like - Profile picture, name , username, dob, height , weight , bmi, gender, phonenumber,  etc. 

But the user database doesn't have all these data, even when you enter it while registering. 
This is because the handling of register button is not done properly. 
The only data that gets an user registered is email and password. 


how the submit is handled. 
![image](https://github.com/user-attachments/assets/35b7200a-b900-4b62-a1d0-aac2d7703533)

how data is stored in firebase 
![image](https://github.com/user-attachments/assets/14ae7d40-3bac-454f-9530-b2a570f40851)
As you can see, only email and password is currently present, even though a user registers with all his details.  


A proper database is needed to be created to be created in order to keep user's information for use on the website.
Furthermore, the register code is to be modified to be incorporate to send all the data to the database for future retrieving. 
The firebase code is also need to be modified to define the schema of the user data.
