### ISSUE TITLE
[Bug]: the about us page is not responsive 

### ISSUE THREAD

**Issue by AyushSharma72** [Open-Code-Crafters/FitFlex#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

below 350px the about us page is not responsive
 due to the image on the navbar i want to fix the image placement so that the page becomes responsive

![Screenshot 2024-10-02 172409](https://github.com/user-attachments/assets/0a5527d9-02fd-4f3d-b420-966dff4075de)

### Expected behavior

the placement of the image should be such that it do not hinder the responsive ness

### Add ScreenShots

![Screenshot 2024-10-02 172859](https://github.com/user-attachments/assets/25a22798-a6fb-4e9a-868f-d6b69323b307)
the footer items are also overflowing

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by AyushSharma72** [comment]
> can you assign this to me I will work on it
please raise other issue this one is already assigned

**Comment by AyushSharma72** [comment]
U can assign it to @uzefaqureshi06 I will not work on this

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by jeevan10017** [comment]
@uzefaqureshi06 go ahead, also resolve horizontal scroll issue
