### ISSUE TITLE
[Bug]: Adding email validation check for Newsletter Subscription 

### ISSUE THREAD

**Issue by Hamza1821** [Open-Code-Crafters/FitFlex#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **at footer the current newsletter subscription button is not checking for the validity of entered email**

![Screenshot 2024-10-15 at 13-11-00 FitFlex Zone-Home](https://github.com/user-attachments/assets/f11456f4-c35b-4d76-9c5e-42114a87460d)

please assign this issue to me under gssoc-ext

### Expected behavior

the subscription button should check weather the entered email is valid or not. if not? it should send a message like "email not valid"

### Add ScreenShots

![Screenshot 2024-10-15 at 13-11-00 FitFlex Zone-Home](https://github.com/user-attachments/assets/5f158ea3-b828-4097-969b-87747d8e64d2)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Hamza1821, please ho ahead.
