### ISSUE TITLE
[Feature Request]: 🚀 [UI Enhancement ] -Adding Gsap Animations to landing page for better UI experinece | gssoc-ext | level 3

### ISSUE THREAD

**Issue by Hamza1821** [Open-Code-Crafters/FitFlex#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### *i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations*

please asign this to me under  gssoc-ext level 3

### Use Case

when the website is loaded then user will see a sliding down navbar with its elemnts having  stagger effect and also hero section text will be having effect of sliding from left and right

### Benefits

it will give user more engaging experience

### Add ScreenShots

NA

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Hamza1821, please provide sample photos of it

**Comment by Hamza1821** [comment]
i request you to visit [https://mmmut-mca.vercel.app/](url)  as it is a project i recently added some gsap animation

### where to find gsap animation?
1) See navbar element when the page is loaded for the first time
2) see hero section left side text , it has a scale up animation which run everytime you return to home page from other pages also when the site is loaded first time

**Comment by GAVINESHWAR** [comment]
@Hamza1821, that's looking good I am assigning you but you do some more better animations to the navbar.

**Comment by Hamza1821** [comment]
Sir i will try my best  but i request you to label it level 3 as integrating gsap to any project is not an easy task

**Comment by GAVINESHWAR** [comment]
@Hamza1821, After submitting the PR i will review and change the level don't worry.
