### ISSUE TITLE
[Bug]: The values for height and weight do not change

### ISSUE THREAD

**Issue by sank8-2** [Open-Code-Crafters/FitFlex#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The values for height and weight in the FitFlex Customer Support does not change with every new request in the same chat.

### Expected behavior

With every request for BMI Calculation, the height and weight need to be updated and show the new BMI

### Add ScreenShots

https://github.com/user-attachments/assets/f5eebeca-0a6d-43b1-9712-114929d83936

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@sank8-2, Please procced with your issue

**Comment by sank8-2** [comment]
When will the PR be reviewed?
