### ISSUE TITLE
[Feature Request]: Changing Hover Color in Footer

### ISSUE THREAD

**Issue by PrAyAg9** [Open-Code-Crafters/FitFlex#245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to change hover color of social media icons in website, like when hovered to facebook it turns blue, instagram turns into gradient, twitter turns black like this.

### Use Case

It would look good.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@PrAyAg9, please add attractive color and hover.
