### ISSUE TITLE
[Feature Request]: Add a BMI calculator

### ISSUE THREAD

**Issue by NK-Works** [Open-Code-Crafters/FitFlex#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a BMI calculator

### Use Case

![image](https://github.com/user-attachments/assets/2361b0ab-00b2-4c33-ac9c-2783d2c92c6f)
in this position
can be used to calculate the BMi of the body builders

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@NK-Works, please provide the image of the calculator to assign the issue.

Thank you

**Comment by NK-Works** [comment]
![image](https://github.com/user-attachments/assets/65a784ef-7f56-4b6a-81ce-3a020ab3adbd)
@GAVINESHWAR something similar to this
