### ISSUE TITLE
footer icon issue

### ISSUE THREAD

**Issue by dipeshkumar799** [Open-Code-Crafters/FitFlex#249]
in footer while hover in facbook-icon, youtube-icon and telegrm icon the color was white but in my opinion i want to make
then while hovering the icon color was chnage according to  real color .mean acctually the facbook color was blue so i make them blue and the u-tube color is red i will make them red and also i will make the while hovering in icon the size willl increase.[

[

https://github.com/user-attachments/assets/7e6682b5-3936-4053-a9a5-c205a5b6712b
 
@akshadgujarkar :pls assign me i will work in that.

**Comment by GAVINESHWAR** [comment]
@dipeshkumar, This issue already assigned to some one closed as complete thank you for your contribution.
