### ISSUE TITLE
[Bug]: Issue in the dependency for react-simple-chatbot, build failing

### ISSUE THREAD

**Issue by sank8-2** [Open-Code-Crafters/FitFlex#251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Bug]: Issue in the dependency for react-simple-chatbot, build failing
The react-simple-chatbot is dependent on styled-components v4 but installed version is v6.1.13

### Expected behavior

Build should happen successfully and pass all the checks

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@sank8-2, why are you open 2 issues for same PR I am closing it as complete.

**Comment by sank8-2** [comment]
It was a different issue, but solved in 1 pr itself

**Comment by GAVINESHWAR** [comment]
No, @sank8-2. The Issue and Pr should be different. The relation should be 1:1, but not M: N relation.
