### ISSUE TITLE
Chatbot Interface alignment

### ISSUE THREAD

**Issue by amitb0ra** [Open-Code-Crafters/FitFlex#257]
Avatar Placement: The avatar images on the left seem to overlap with the text bubbles. This could be fixed by adjusting the padding or margin between the avatar and the text bubbles.

![image](https://github.com/user-attachments/assets/8ea72627-462d-4d77-b1bc-f26317ce744e)

Suggested Fixes:
Add padding/margin between avatars and message bubbles.
Adjust padding inside message bubbles to increase space around the text.
Ensure consistent vertical spacing between user and bot messages.
Add left padding/margin to user message bubbles and right padding/margin to bot messages to avoid them sticking to the window's edges.

**Comment by GAVINESHWAR** [comment]
@amitb0ra, closed as completed thank you for the contribution.

**Comment by amitb0ra** [comment]
where? its not updated in live site.
also you have missing asset

**Comment by GAVINESHWAR** [comment]
> where? its not updated in live site. also you have missing asset

@amitb0ra, someone working on the Avatar, after completing it I can go for other updates
