### ISSUE TITLE
[Bug]: Social Media account are Not linked

### ISSUE THREAD

**Issue by Prathameshzad** [Open-Code-Crafters/FitFlex#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking social media icons in the footer doesn't redirect the user to the respective social media pages.

### Expected behavior

When a user clicks on the social media account icon then that user should redirect to that particular social media account 

### Add ScreenShots

Clicking on any social media icon should redirect the user to the corresponding social media account page in a new tab or window.

### On which device are you experiencing this bug?

Android, Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Prathameshzad, closed as complete #258.

Thank you for the contribution.
