### ISSUE TITLE
[Documentation Update]: Adding All Contributors Profile Photos in Readme.md file

### ISSUE THREAD

**Issue by say-het** [Open-Code-Crafters/FitFlex#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Issue Description**

 - It lacks Contributors Profiles in Readme.md
 - It should be Like the image that I have shared
 - Hey! @jeevan10017 I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

### Suggested Change

 **I will add this type of Live Contributor Profile Photos in it**
![image](https://github.com/user-attachments/assets/c109d3d6-a375-493e-a01b-aaf9370d603c)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@say-het . go ahead. I will assess your performance and assign a label to your score based on your work in the pull request. If possible try to enhance more which were required in readme file.
