### ISSUE TITLE
[Bug]: Width of pages for mobile view

### ISSUE THREAD

**Issue by jainaryan04** [Open-Code-Crafters/FitFlex#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the pages are not filling the entire width of the page for mobile view

![image](https://github.com/user-attachments/assets/bf9e4ce5-1eef-4a24-a329-0b0b026ec47c)

### Expected behavior

the pages should fill the entire width of the page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/448c0d3b-c2ec-48b0-8388-a2188254dc83)

### On which device are you experiencing this bug?

Android, iPhone

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@jainaryan04, please procced and try to finish as soon as possible and add the photos of changes you done

**Comment by jainaryan04** [comment]
![image](https://github.com/user-attachments/assets/fc055eec-a8da-4853-b2d3-f165edfeb9fe)
@GAVINESHWAR
