### ISSUE TITLE
SEO Optimization of the FitFlex

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#265]
![image](https://github.com/user-attachments/assets/fd3ba406-aa79-44e0-aee3-03230e68d5c2)

The SEO Score of the website is literally poor.
I want to enhance the SEO score.

**Comment by GAVINESHWAR** [comment]
@Shariq2003, Can you explain how will enhance it.

**Comment by Shariq2003** [comment]
> @Shariq2003, Can you explain how will enhance it.

By following the best practices of SEO like :-

1. by Creating a sitemap.xml file to help search engines discover Fitflex pages, and configure a robots.txt file to control crawler access to certain parts of your site.
2. Optimising  Rendering by React lazy loading and Suspense for code-splitting

and more practices as per the web app structure

**Comment by GAVINESHWAR** [comment]
@Shariq2003 , please go ahead.

**Comment by Shariq2003** [comment]
@GAVINESHWAR please review my PR
