### ISSUE TITLE
[Feature Request]: Prevent Page Reload on "Send Message" and Add Success Toast Notification

### ISSUE THREAD

**Issue by akshadgujarkar** [Open-Code-Crafters/FitFlex#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Current Behavior: 
 --> When the "Send Message" button is pressed, the page reloads, disrupting the user experience and providing no immediate feedback regarding the success of the message submission.

Expected Behavior:
 1)On pressing the "Send Message" button, the page should not reload.
 2)Instead, a toast notification should appear confirming that the message has been sent successfully.

### Use Case

Implementing this feature will significantly improve the user experience by eliminating unnecessary page reloads, which disrupt the flow of the application. The addition of a toast notification provides immediate visual feedback, ensuring users know when their message has been successfully sent.

### Benefits

 Improve the user experience by eliminating unnecessary page reloads, which disrupt the flow of the application.

### Add ScreenShots

https://github.com/user-attachments/assets/62317500-23c6-4e07-be56-dc896e674b17

To prevent the above situation which we can see in the video When the "Send Message" button is pressed, the page reloads, disrupting the user experience and providing no immediate feedback regarding the success of the message submission.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [x] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by akshadgujarkar** [comment]
@GAVINESHWAR  kindly review the PR. if any changes let me know

**Comment by akshadgujarkar** [comment]
Hi, I wanted to provide an update regarding this issue. I am currently unable to work on it due to a new issue I've encountered with the cloning process caused by an invalid file path in the .github/workflows directory. Pls solve that issue #295 . By resolving this issue then only I will able to clone this repo and started working issue #269 . 

Please do not close this issue; I intend to solve this issue once the new issue #295  is fixed. Thank you for your understanding!

**Comment by GAVINESHWAR** [comment]
@jeevan10017, many of the contributors are getting the same issue

**Comment by jeevan10017** [comment]
@akshadgujarkar @GAVINESHWAR  once confirm it. Is this issue solved ?.

**Comment by GAVINESHWAR** [comment]
I Think it is not solved I will clone once and check it.

**Comment by akshadgujarkar** [comment]
@GAVINESHWAR  , @jeevan10017 pls solve  issue #295 because i really wanna contribute to FitFlex repo but facing lots of problem while cloning

**Comment by jeevan10017** [comment]
@akshadgujarkar I have removed that GitHub workflows path.

**Comment by akshadgujarkar** [comment]
@jeevan10017  Thank you so much
