### ISSUE TITLE
[Feature Request]: Update the styling of sidebar(scrollbar for the entire website that matches with the website theme)

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Modify the scrollbar that mathces the theme of the website and make the whole tab/windows looks user friendly and attractive.

### Use Case

Improve User Experience
Improve UI
Improve the whole website

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c36f827c-a76d-4d1e-bd1d-060b147c178e)
Sidebar looks weird 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Shariq2003 go ahead. "I will assess your performance and assign a label to your score based on your work in the pull request.
