### ISSUE TITLE
Services Section

### ISSUE THREAD

**Issue by Bhum-ika** [Open-Code-Crafters/FitFlex#275]
**Contributor Information**
Please check if you are a contributor from: 
- [x] GSSoC-ext
- [x] Hacktoberfest

![image](https://github.com/user-attachments/assets/fa890036-2c97-4967-8890-a9fb7bdaa4b4)

The buttons are misaligned and the whole content on card is in bold, only heading should be in bold and other content should be smaller respectively 
There is no hover effect on button

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by GAVINESHWAR** [comment]
@Bhum-ika, please go through it add make better UI.

**Comment by sameer-soni** [comment]
@GAVINESHWAR if there is no update, can I get assigned?

**Comment by Bhum-ika** [comment]
I am working on it

**Comment by GAVINESHWAR** [comment]
@Bhum-ika , Weather you are cloning from current project or forked project.

**Comment by Bhum-ika** [comment]
I am cloning from forked one

**Comment by Bhum-ika** [comment]
Got it, working on the issue now
