### ISSUE TITLE
[Bug]: Password length visible in login page

### ISSUE THREAD

**Issue by Gauravtb2253** [Open-Code-Crafters/FitFlex#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The minimum length of password is visible in login page
This should not happen

### Expected behavior

Only the message for invalid password should be shown

### Add ScreenShots

![image](https://github.com/user-attachments/assets/43d29bb9-5c68-42ce-ba00-e8685fd21e2f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Gauravtb2253, I am not getting your exact thing could you please specify in detail..

**Comment by Gauravtb2253** [comment]
The password length should be visible while registering and not while login
Like if someone tries to access other persons account he will get to know that the password is of x length
So it is not a good practice for security reasons to show the length in login page

**Comment by Gauravtb2253** [comment]
can you pls add level2 label

**Comment by GAVINESHWAR** [comment]
Please add the changes photo

**Comment by Gauravtb2253** [comment]
actually I am getting error in installing node_modules
But I have changed the error message in the zod validation schema
You can check there

![image](https://github.com/user-attachments/assets/f3766fb4-aade-45ed-a7c9-50edd3b68f27)

this is the error
