### ISSUE TITLE
[Feature Request]: Implementation of "Forgot Password" Page

### ISSUE THREAD

**Issue by SRV30** [Open-Code-Crafters/FitFlex#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "Forgot Password" feature allows users who have forgotten their passwords to reset them, enhancing user experience and account security securely. This feature minimizes user frustration and increases the likelihood of user retention by providing a straightforward recovery process.

### Use Case

"Forgot Password" feature not only enhances user experience but also contributes to the security and credibility of the project. 

### Benefits

To enhance user experience and security by allowing users to reset their passwords if they forget them.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by SRV30** [comment]
Please assigned me this work.

**Comment by GAVINESHWAR** [comment]
@SRV30, how you were going to add that feature could please explain detail.

**Comment by SRV30** [comment]
@GAVINESHWAR Sorry for the late reply. In this repo, the Firebase database is used. I will use the Firebase reset link for password resetting when the user submits the "Forgot Password" button.

Examples of images are provided below:

![image](https://github.com/user-attachments/assets/a55c6007-5549-4025-bef3-ddcb37324b56)

![image](https://github.com/user-attachments/assets/6f536d03-1c94-44f0-90a5-8db7631dc0ea)


![image](https://github.com/user-attachments/assets/8f25f8f3-47a8-4d38-bafe-ce48a7c5dc5c)

I will fix the template and design once this task is assigned to me.
