### ISSUE TITLE
Add animation to enhance smoothness 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#293]
**Contributor Information**
Please check if you are a contributor from:
- [ ✅] GSSoC-ext
- [✅ ] Hacktoberfest

add animation through out the website for better user experience and also it increase the smothness of website

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, please add relavante sample images of the enhancement.

**Comment by Sawan-Kushwah** [comment]
@GAVINESHWAR currently I don't have any sample but you can assign me this I will not disappoint you!!
