### ISSUE TITLE
[Documentation Update]:  Add GitHub Repository Stats to README.md

### ISSUE THREAD

**Issue by REHAN-18** [Open-Code-Crafters/FitFlex#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.

### Suggested Change

Steps to Implement:

Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.
<img width="817" alt="Screenshot 2024-10-21 at 11 04 49 PM" src="https://github.com/user-attachments/assets/99f79a64-a5ba-48e4-ba30-85fd164bcd77">

### Rationale

Expected Behavior:

The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

Additional Information:

This enhancement will make the repository more user-friendly by providing visibility into its overall activity.
The table can be dynamically updated by using GitHub shields or other badge services to fetch real-time stats

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by krichen-Noureddine** [comment]
I would like to work on this issue. Could I be assigned?

**Comment by GAVINESHWAR** [comment]
@REHAN-18 , please go ahead.

**Comment by REHAN-18** [comment]
@GAVINESHWAR bro I have done the pls see pr #310 & merge it
