### ISSUE TITLE
Footer is not responsive in mobile view 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#303]
![Screenshot_20241022_082046](https://github.com/user-attachments/assets/dc9dc0eb-d16f-468c-a1ef-c5f288b62994)

Assign me i can work on it 

**Contributor Information**
Please check if you are a contributor from:
- [ X] GSSoC-ext
- [ X] Hacktoberfest

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, I am already assigned the same kind of issue so please wait couple of days.
