### ISSUE TITLE
[Bug]: fix the heading issue in mobile view 

### ISSUE THREAD

**Issue by AE-Hertz** [Open-Code-Crafters/FitFlex#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Fix the issue of text not showing inmobile view

Assign me this under hacktoberfest and gssoc-ext.

### Expected behavior

![Screenshot_2024-10-22-12-36-17-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/17a381c7-f60b-4899-80ef-68aafbfc904a)
The text heading should be visible.

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@AE-Hertz, please explain me what changes would you like to do in it.

**Comment by AE-Hertz** [comment]
@GAVINESHWAR as I already mentioned but let me elaborate, refer to the screenshot i attached and the text is overlapped by fitflex logo, so I am going to make the text visible by tuning the styling, either by moving the text down little bit or by minimising the fitflex logo after certain amount of time.

**Comment by GAVINESHWAR** [comment]
@AE-Hertz,Ok proceed.
