### ISSUE TITLE
[Feature Request]: Subscribe to the Platform

### ISSUE THREAD

**Issue by haseebzaki-07** [Open-Code-Crafters/FitFlex#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

users should get a email for confirmation when they subscribe the platform. This is a must feature for having for a website like this.
Also it will help users to keep track for the updates for the services on the website.

### Use Case

This is a must feature for having for a website like this.
Also it will help users to keep track for the updates for the services on the website.

### Add ScreenShots

![Screenshot 2024-10-22 132457](https://github.com/user-attachments/assets/39212478-2c68-441e-9609-aba618274a57)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@haseebzaki-07, please explain me how you are going to do it.

**Comment by haseebzaki-07** [comment]
@GAVINESHWAR  so I will use nodemailer,  a npm package used to send mails, I will write the controller for the purpose that will be having a email and pass from which the mail will be sent and i.e the sender's mail and the receiver's mails will be retrieved form the input fields and the API will send the mail to the respective users.

**Comment by GAVINESHWAR** [comment]
Ok please continue
