### ISSUE TITLE
Stats section not responsive

### ISSUE THREAD

**Issue by swathivemula7** [Open-Code-Crafters/FitFlex#314]
Stats section is not responsive in the mobile version and half the content is not visible...I would like to fix this...

![IMG_20241022_230926](https://github.com/user-attachments/assets/3babdb90-5911-4a80-8132-8c518c6b54cc)

@GAVINESHWAR Kindly assign me this issue under labels gssoc and hacktoberfest...

**Comment by GAVINESHWAR** [comment]
Ok @swathivemula7, please complete it as soon as possible.
