### ISSUE TITLE
Pages not aligned 

### ISSUE THREAD

**Issue by Rajput-xv** [Open-Code-Crafters/FitFlex#316]
Have a look at the Screenshots as we can see that the pages are not aligned to navbar properly.
Some content is hiding.

![image](https://github.com/user-attachments/assets/64e6ef4f-a3ec-46a6-8285-7c5fe6574e7e)

![image](https://github.com/user-attachments/assets/93c8cc02-0719-4e62-969f-f770a0433c35)

![image](https://github.com/user-attachments/assets/82690979-23eb-44a9-87df-3f317ef38c41)

@GAVINESHWAR kindly assign me this issue.

Thank you.

**Contributor Information**
Please check if you are a contributor from:
- [X ] GSSoC-ext
- [X ] Hacktoberfest

**Comment by GAVINESHWAR** [comment]
@Rajput-xv, please proceed.
