### ISSUE TITLE
Responsiveness Issues, navbar problem and meta tags

### ISSUE THREAD

**Issue by vivek7156** [Open-Code-Crafters/FitFlex#319]
**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

![Screenshot 2024-10-23 103707](https://github.com/user-attachments/assets/5acb241a-d39f-4d86-a700-3a21552949dc)

Responsiveness Issues: On smaller screens, text, images, and buttons are not displaying correctly, which makes the alignment and usability bad. This can be fixed with proper media queries and flexible layouts.

Navigation Bar Problem: The navigation bar lacks visibility, making it hard for users to find essential links. A sticky or more prominent design would improve accessibility and also it overlaps with the content on many pages.

![Screenshot 2024-10-23 103814](https://github.com/user-attachments/assets/58086b84-0cf6-4ba0-b27c-c27e9853deb4)

**Comment by GAVINESHWAR** [comment]
@vivek7156, please proceed.
