### ISSUE TITLE
[Feature Request]: Adding a Carousel to Show team members at About us Page

### ISSUE THREAD

**Issue by IkkiOcean** [Open-Code-Crafters/FitFlex#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The "About Us" page currently lacks an engaging way to showcase our team members. I propose adding a carousel that will display the profiles of our team members, enhancing user experience and providing visitors with a more dynamic view of our staff.

### Use Case

- Improve the visual appeal of the "About Us" page.
- Allow visitors to easily learn about our team without overwhelming them with information.
- Enhance engagement by making the page more interactive.

### Add ScreenShots

https://github.com/user-attachments/assets/20bda762-95b0-47d9-8abf-13372a241e9e

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@IkkiOcean, please go ahead
