### ISSUE TITLE
Scrollbar is missing in all pages of website

### ISSUE THREAD

**Issue by swathivemula7** [Open-Code-Crafters/FitFlex#334]
There is no scrollbar all over the website in all pages. So we are only able to scroll using keyboard keys.I would like to add scrollbar in all pages of the website..

@GAVINESHWAR Kindly assign me this issue under the gssoc and hacktoberfest labels...

**Comment by GAVINESHWAR** [comment]
@swathivemula7, Please add reference photos.

**Comment by swathivemula7** [comment]
![Capturedef](https://github.com/user-attachments/assets/ba4f46d4-864d-4433-bc96-135a0c60522e)
@GAVINESHWAR I would like to add a scrollbar at the right end mentioned in the picture to scroll the page, similarly in all pages of the website

**Comment by swathivemula7** [comment]
![Capturefrg](https://github.com/user-attachments/assets/093fdba3-ba5c-4b9e-a9ad-c13ba8ca04fc)
I would like to add a scrollbar at the right end of the website, to scroll down...
reference:
![Capturedv](https://github.com/user-attachments/assets/12094fea-755c-4e6c-a3b1-80ab0ddef457)

**Comment by GAVINESHWAR** [comment]
@swathivemula7, please proceed.
