### ISSUE TITLE
[Feature Request]: Upload blog feature for authenticated users

### ISSUE THREAD

**Issue by ShivanshPlays** [Open-Code-Crafters/FitFlex#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

# Issue Description: Upload Blog Feature for Authenticated Users

## Overview

The purpose of this feature is to implement an "Upload Blog" functionality that allows authenticated users to create and publish blog posts on the platform. This will enhance user engagement by enabling content creation directly from users.

## Requirements

**Authentication Check:**
   - Only authenticated users should be able to access the upload blog feature. Implement checks to ensure users are logged in before they can upload a blog post.

**Blog Post Form:**
   - Create a user-friendly form that includes the following fields:
     - Title (required)
     - Content (required)
   - Ensure the form has appropriate validation to handle user input.

 **Save to Database:**
   - Upon successful submission, save the blog post to the database, associating it with the authenticated user's ID.

 **Success/Error Notifications:**
   - Implement notifications to inform users of successful uploads or errors during the submission process.

## Acceptance Criteria

- Users must be authenticated to access the upload blog feature.
- The blog post form must validate input fields correctly.
- Users should receive feedback upon successful upload or error messages when submissions fail.

## Additional Notes

- Ensure responsiveness and usability across different devices.

## Benefits

- Enhances user engagement by allowing authenticated users to contribute content.
- Increases the platform's content diversity and richness.
- Fosters a sense of community and interaction among users.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@ShivanshPlays, please add the reference photos

**Comment by ShivanshPlays** [comment]
@GAVINESHWAR I will design and add the page, I'll link the screen recording for the working feature in the PR, can you please consider assigning me this feature request under gssoc, thanks.

**Comment by GAVINESHWAR** [comment]
@ShivanshPlays, proceed
