### ISSUE TITLE
[Bug]: navbar is not responsive for small screen devices

### ISSUE THREAD

**Issue by Navneetdadhich** [Open-Code-Crafters/FitFlex#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to improve the navbar responsiveness for small screen devices.

### Expected behavior

the text and the logo should be proper for all the mobile devices. 

### Add ScreenShots

![fitflex](https://github.com/user-attachments/assets/b80a4b12-7c97-4427-b512-9d7f56fa7a7d)

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Nvntdad  #35  By changing single lines of code, you cannot create a pull request according to the rules.

**Comment by Nvntdad** [comment]
in what context you talking about.

**Comment by jeevan10017** [comment]
> in what context you talking about.

I was saying about merge #35 issue in this issue.

**Comment by Nvntdad** [comment]
okay okay mybad i dont know that things can also work like this, today i contributed around 5 features in a single PR but then the owner said you can't contribute like this and closed the PR, thats why i have raised here two different issue.

**Comment by Nvntdad** [comment]
can i include footer icons responsiveness with these two issues.

**Comment by jeevan10017** [comment]
@Nvntdad go ahead
