### ISSUE TITLE
[Feature Request]: Setup Backend Functionality: setting up BE project and implementing signup functionality

### ISSUE THREAD

**Issue by ShivanshPlays** [Open-Code-Crafters/FitFlex#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

# [Feature Request]: Setup Backend Functionality for Authentication

## Issue Overview

The current authentication setup in the application is ambiguous and not functioning correctly. To enhance user management and security, I propose **removing the existing authentication** system and **rebuilding it with a proper backend**. This will allow us to manage authentication more effectively and streamline the entire login/signup experience.

## Suggested Solutions

We can implement the backend using the following technologies:

### **1. Next.js**  
- **Why Next.js?**  
  - Built-in API routes for server-side logic.
  - Seamless integration with frontend and backend in one codebase.
  - Easy deployment with **Vercel**.

### **2. Hono**  
- **Why Hono?**  
  - Extremely lightweight and fast.
  - Ideal for small-scale, serverless applications.
  - Simple API structure, easy to learn, and supports Edge functions.

**Recommendation**: I suggest using either **Next.js**  for ease of deployment and scalability.

## Frontend Deployment

- The frontend deployment can remain **as it currently is**.
- The backend will be hosted separately can it can be connected to the current frontend by passing the BE url as an env variable

## Scope of Work

1. **Remove the current broken authentication setup**.
2. **Implement backend authentication logic** using one of the suggested frameworks.
3. **Setup endpoints for user registration, login, and session management**.
4. **Deploy and test the new authentication system** with the existing frontend.
5. Ensure smooth redirection and user experience after login/logout.

### Use Case

- A more **robust and maintainable authentication** system.
- **Secure user data management** on the server side.
- **Better scalability** for future features such as token-based authentication (JWT) or OAuth.

### Acceptance Criteria

- [ ] Current authentication system is removed.
- [ ] Backend authentication is implemented using Next.js / Hono / Express.
- [ ] API endpoints for signup, login, and logout are functional.
- [ ] Integration with frontend is tested and works seamlessly.
- [ ] New backend is deployed and verified for production readiness.

---

### Additional Information

- Ensure that user session management works properly with the new backend.
- Use **environment variables** for sensitive information (e.g., API keys, secret tokens).
- Follow **security best practices** to protect user data and prevent common vulnerabilities.

---

### References

- [Next.js Documentation](https://nextjs.org/docs)
- [Hono Documentation](https://hono.dev/)
- [Express.js Documentation](https://expressjs.com/)

---

### Labels

- `feature request`
- `backend`
- `authentication`

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by ShivanshPlays** [comment]
@jeevan10017 please review and assign, also please choose a framework to start with, I have provided my suggestions also

**Comment by jeevan10017** [comment]
@Sami3160

**Comment by ShivanshPlays** [comment]
@jeevan10017 ?

**Comment by Sami3160** [comment]
> @jeevan10017 ?


Sry but we cannot implement backend for this project in any technology,
