### ISSUE TITLE
[Feature Request]:  Set Up Firebase for Backend

### ISSUE THREAD

**Issue by 17arindam** [Open-Code-Crafters/FitFlex#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to integrate Firebase as the backend for our project to manage authentication, database, and other services such as Firestore, Cloud Functions, and Firebase Hosting (if necessary). Firebase provides a scalable, real-time database and is a great solution for managing user authentication, data storage, and real-time updates.

### Use Case

It can be uesd for user registration, sign in and can be used as a database.

### Benefits

Firebase provides a scalable, real-time database and is a great solution for managing user authentication, data storage, and real-time updates.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@17arindam, I appreciate your interest👏. However, someone is already working on this (issue - 18). You can raise another issue, and kindly review the currently active issues.
