### ISSUE TITLE
[Feature Request]: Make "Like" Feature Dynamic on Services Page Cards

### ISSUE THREAD

**Issue by akshadgujarkar** [Open-Code-Crafters/FitFlex#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On the Services page, each card currently displays two static options: "Views" and "Like." To enhance user interactivity, I propose making the "Like" feature dynamic.

### Use Case

As a user visiting the FitFlex website, I want to be able to engage with the Services page by liking or unliking specific service cards, so that I can express my interest in particular services.

1)  Scenario: When I view a service card, I see options to view or like it.
2)  Action: I click the "Like" button on a card.
3)  Outcome: The like count on that card increments by one, and the "Like" button changes to "Unlike," allowing me to retract 
            my like if desired.
4)  Restriction: I am allowed to either like or unlike a card, but not both simultaneously.

### Benefits

This use case improves interactivity on the Services page, encouraging user engagement and providing valuable feedback on popular services.

### Add ScreenShots

<img width="924" alt="2" src="https://github.com/user-attachments/assets/8bdd6701-80c9-46b8-b7ee-1db375a6ba45">
--> I marked the section with red pen and highlighted it with yellow color which I want to change. Make is dynamic

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by akshadgujarkar** [comment]
could you pls assign this issue to me I am really wanna work on it

**Comment by GAVINESHWAR** [comment]
@akshadgujarkar, proceed
