### ISSUE TITLE
[Bug]: Upper content get hidden under navbar

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/user-attachments/assets/43344a00-1c37-4da8-b185-14d7b50e3640)

as you can see some content of the page get hidden under navbar 
this decrease the user experience and also look and feel of website 

### Expected behavior

Content should be visible clearly not only on this page it is present everywhere

i can fix it in all page

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, please proceed.
