### ISSUE TITLE
[Feature Request]: AI based chatbot

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/0bac06a1-b64a-4138-83c2-86749c196656)

it is rule based chatbot which will answer specifically 

### Use Case

i can implement a AI based chatbot which will be trained on our website data and answer through his own intelligence 

### Benefits

better user experience 
sample chatbot 

https://github.com/user-attachments/assets/67f53e9c-3a04-4b9a-8048-c6b269aea98c

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, proceed.
