### ISSUE TITLE
[Feature Request]: our contributor page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I can build our contributor page!!

### Use Case

Here we show the hard work of our developer in both light and dark theme
And state of our repo
And attract more developers to work on our project 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/13586955-3208-410f-84e4-88c20b61f0ae

@GAVINESHWAR  i can redesign according to our website theme

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, proceed.
