### ISSUE TITLE
[Feature Request]: Addition of Customer Support | Chatbot Bubble

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/69cff656-b167-4d75-89e7-0e28f2f55153)

We can add a Chatbot Suport for Personalize support to customer similar to the above image.
Initially, I can add the Bubble Chatbot Icon on the Website,
Later, that can extend to integrate with the bot in the future to communicate with the customer.

### Use Case

Enhance the UI and UX

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Shariq2003 updates?

**Comment by Shariq2003** [comment]
> @Shariq2003 updates?

Will raise a PR soon, maybe by 2 am today.

**Comment by Shariq2003** [comment]
@jeevan10017 I am sorry, actually I was unable to work on this issue due to backlogs but now I will definitely complete this and want to continue to this issue, Please open this issue.

**Comment by jeevan10017** [comment]
@Shariq2003 go ahead

**Comment by jeevan10017** [comment]
Don't just show the icon. I will increase your level based on your work

**Comment by Shariq2003** [comment]
okay

**Comment by Shariq2003** [comment]
> Don't just show the icon. I will increase your level based on your work

You want a chatbot integration ?

**Comment by Shariq2003** [comment]
> Don't just show the icon. I will increase your level based on your work

What can I do is, for a chatbot (working), have to integrate a Model like (chatgpt, or dialogflow)

**Comment by Shariq2003** [comment]
@jeevan10017 sir, please let me know asap, so that I can start wokring

**Comment by jeevan10017** [comment]
> > Don't just show the icon. I will increase your level based on your work
> 
> You want a chatbot integration ?

Yes, if you can

**Comment by Shariq2003** [comment]
> > > Don't just show the icon. I will increase your level based on your work
> > 
> > 
> > You want a chatbot integration ?
> 
> Yes, if you can

Lets connect on LinkedIn for API key, I want an API key for the ChatGPT or dialogue flow

**Comment by jeevan10017** [comment]
@Shariq2003 first make it if you have an API Key. Do the screen record for the demo. And remove it before raising PR.

**Comment by Shariq2003** [comment]
> @Shariq2003 first make it if you have an API Key. Do the screen record for the demo. And remove it before raising PR.

Okay

**Comment by Shariq2003** [comment]
https://github.com/user-attachments/assets/9bee1649-ef13-4f2a-96a8-96d4be4344d7

@jeevan10017 please review this, I have add a custom chatbot flow for the Fitflex using react-simple-chatbot and added that in the website.

**Comment by jeevan10017** [comment]
> bandicam.2024-10-11.01-54-57-653.mp4 
> @jeevan10017 please review this, I have add a custom chatbot flow for the Fitflex using react-simple-chatbot and added that in the website.

awesome 👏, have you done this with the  JSON / API?

**Comment by Shariq2003** [comment]
> > bandicam.2024-10-11.01-54-57-653.mp4
> > @jeevan10017 please review this, I have add a custom chatbot flow for the Fitflex using react-simple-chatbot and added that in the website.
> 
> awesome 👏, have you done this with the JSON / API?

JSON sir

**Comment by Shariq2003** [comment]
Can i create a PR now for this.

**Comment by jeevan10017** [comment]
> Can i create a PR now for this. Or if u want to give me your own flow (if u have created) then I can add that too else this is also good I think

I don't have right now
use some more length of the flow, Create by using GPT.
and then we can upgrade later with stategic flow.
ok, you can Create PR after it.

**Comment by Shariq2003** [comment]
@jeevan10017 check now
