### ISSUE TITLE
[Bug]: Issues with about us page

### ISSUE THREAD

**Issue by shamvrueth** [Open-Code-Crafters/FitFlex#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Few boxes displayed in the about us page have overflowing text. While switching to dark mode, 2 boxes are disappearing from the page

### Expected behavior

The text shouldn't overflow. Boxes shouldn't disappear when switching to dark mode.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/a6fc532f-b693-4240-8f96-9874f39e4585)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@shamvrueth, please proceed
