### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by ShreyaSnehal** [Open-Code-Crafters/FitFlex#38]
There is overlap of social media icons and arrow (go to top of page) on the right down corner in the footer section .

**Contributor Information**
Please check if you are a contributor from:
- [ ] GSSoC-ext
- [ ] hacktoberfest-excepted 

![image](https://github.com/user-attachments/assets/928ae072-5228-48a5-bb6c-34c54a5610af)

**Comment by jeevan10017** [comment]
@ShreyaSnehal, what do you want to change in this? Describe it. and also, make a mark you are from Assoc-ext / hacktoberfest or both.

**Comment by ShreyaSnehal** [comment]
I can change the entire  footer and also shift the "back to top" in the middle bottom so that it does not overlaps other elements.
assign this to me and tag it as GSSoc-ect and hacktoberfest

**Comment by jeevan10017** [comment]
@ShreyaSnehal Ok go ahead
