### ISSUE TITLE
Title: Enhance Body Parts Categories UI with GIFs

### ISSUE THREAD

**Issue by rajlakshmi18704** [Open-Code-Crafters/FitFlex#40]
#40
Currently, the UI for the body parts categories displays static images, which could be further improved to create a more engaging user experience. I suggest replacing these static images with GIFs that demonstrate exercises for each body part. Not only will this make the interface more visually appealing, but it will also provide users with dynamic content that showcases exercises in action, ultimately enhancing their overall experience.

Proposed Changes:
GIF Integration: Replace static images with relevant GIFs for each body part category. I have GIFs available in the .json file that can be utilized for this purpose.

User Experience: This change will not only attract users' attention but will also help them visualize the exercises better, potentially increasing user engagement and satisfaction.

I want to enhance this UI part.
![Screenshot (121)](https://github.com/user-attachments/assets/43f6e812-0f70-4d42-9ad6-9c366894c8b4)

I want to contribute this issue under hactoberfest and GSOC-EXT

I am willing to work on this.Kindly assign it to me.

**Comment by jeevan10017** [comment]
@rajlakshmi18704 go ahead👍
 Your level may change based on the quality of your work when merging pull requests.

**Comment by Sami3160** [comment]
> #40 Currently, the UI for the body parts categories displays static images, which could be further improved to create a more engaging user experience. I suggest replacing these static images with GIFs that demonstrate exercises for each body part. Not only will this make the interface more visually appealing, but it will also provide users with dynamic content that showcases exercises in action, ultimately enhancing their overall experience.
> 
> Proposed Changes: GIF Integration: Replace static images with relevant GIFs for each body part category. I have GIFs available in the .json file that can be utilized for this purpose.
> 
> User Experience: This change will not only attract users' attention but will also help them visualize the exercises better, potentially increasing user engagement and satisfaction.
> 
> I want to enhance this UI part. ![Screenshot (121)](https://private-user-images.githubusercontent.com/122472826/373209166-43f6e812-0f70-4d42-9ad6-9c366894c8b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Nzg4MzIsIm5iZiI6MTcyNzk3ODUzMiwicGF0aCI6Ii8xMjI0NzI4MjYvMzczMjA5MTY2LTQzZjZlODEyLTBmNzAtNGQ0Mi05YWQ2LTljMzY2ODk0YzhiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxODAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzUyODMwNjcwZmM4YTZiYjg1MmFmNjEzNjIzOWY5ZWMxYzM4MmYwZjhiOTMxZDU0ZDZiZDgwNzljZGExMDI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nsEvK0eIiKQEQU04csJuIGTCGjGT5uuFu1HpTD_5Vw0)
> 
> I want to contribute this issue under hactoberfest and GSOC-EXT
> 
> I am willing to work on this.Kindly assign it to me.

hello @rajlakshmi18704 whatever gif you are willing to add, keep updating the json files also,
