### ISSUE TITLE
[Feature Request]: Backend implementation for add,edit and delete review 

### ISSUE THREAD

**Issue by Meetpidev** [Open-Code-Crafters/FitFlex#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Backend implementation for add,edit and delete review 

### Use Case

To display reviews...

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@GAVINESHWAR we can add feature like ..user can add delete and edit review..

**Comment by GAVINESHWAR** [comment]
Our project is developed using the firebase, So are you aware of it

**Comment by Meetpidev** [comment]
Yeah

**Comment by GAVINESHWAR** [comment]
@Meetpidev, proceed.

**Comment by Meetpidev** [comment]
Till then can i fix other issues that i created ?

**Comment by GAVINESHWAR** [comment]
yes

**Comment by Meetpidev** [comment]
@GAVINESHWAR So please assign me that issue also..

**Comment by GAVINESHWAR** [comment]
@Meetpidev, I am already assigned you

**Comment by Meetpidev** [comment]
@GAVINESHWAR What about the issue of #403 and #401 ??

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR.. i implemented it..

**Comment by Meetpidev** [comment]
@GAVINESHWAR 
### Requested To Review PR...

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR...
