### ISSUE TITLE
[Bug]: margine ,padding issue in pages

### ISSUE THREAD

**Issue by Meetpidev** [Open-Code-Crafters/FitFlex#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In all the pages there are margin-padding isuue.. its not set properly as the result some portion is hide from the top.. like in about us page the first title "your fitness, your future" is invisible.. 

### Expected behavior

Need proper margin and padding in every pages.. so that all the information is visible..

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Meetpidev, proceed
