### ISSUE TITLE
Receive contact us details on EMAIL instantly for faster response to user

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i can implement this feature where you will receive this info instantly on mail 

### Use Case

for instant response to user
enhance user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, I think this is not required now
