### ISSUE TITLE
[Bug]: Issue in current code

### ISSUE THREAD

**Issue by Meetpidev** [Open-Code-Crafters/FitFlex#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Whe i go to the code i found that there is an error in src/views/Blog.jsx. in that mode is not defined.
### Add ScreenShots

![image](https://github.com/user-attachments/assets/28251fc7-6cf2-42e3-a525-32b8c2abc388)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Meetpidev, please resolve the issue.

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR
