### ISSUE TITLE
[feature]: Create Health tips page

### ISSUE THREAD

**Issue by Jay-1409** [Open-Code-Crafters/FitFlex#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we tap on the logo of the website it wont redirect back to home

### Expected behavior

The logo button should redirect to the home page

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Jay-1409 changing a line of code can't be counted as a contribution. Raise another issue which you can do together in the same issue.

**Comment by Jay-1409** [comment]
i will create the health tips page too

**Comment by jeevan10017** [comment]
@Jay-1409, please describe it briefly with reference images. so that I can assign you with level.

**Comment by Jay-1409** [comment]
The health tips page would include the following 

- **Stay Hydrated:** Drink plenty of water throughout the day, especially before, during, and after workouts. Proper hydration aids in muscle recovery and prevents fatigue.

-**Consistency Over Intensity:** Regular, moderate exercise is more effective for long-term fitness than occasional intense workouts. Aim for at least 150 minutes of moderate or 75 minutes of vigorous exercise weekly.

-**Strength Training:** Include strength training exercises 2-3 times per week to build and maintain muscle mass. Focus on full-body exercises like squats, lunges, and push-ups.

-**Warm-Up and Cool Down:** Always start your workout with a warm-up to increase blood flow and prepare your muscles. Finish with a cool-down and stretching to aid in flexibility and recovery.

-**Balanced Diet:** Fuel your body with a balanced diet rich in whole grains, lean proteins, fruits, vegetables, and healthy fats. Proper nutrition is key to achieving fitness goals and promoting overall well-being.

-**Rest and Recovery:** Give your muscles time to recover by getting adequate sleep (7-9 hours) and scheduling rest days between intense workouts. Overtraining can lead to injuries and burnout.

-**Mix Up Your Routine:** Keep your workouts interesting by trying activities like cycling, swimming, yoga, or HIIT (High-Intensity Interval Training). This prevents boredom and challenges different muscle groups.

-**Posture and Form:** Pay attention to your posture and form during exercises to prevent injury. If unsure, consider working with a fitness trainer to correct any mistakes.

-**Mental Health:** Fitness isn't just physical. Practices like yoga, meditation, or simple stretching routines can help improve mental well-being and reduce stress.

The page layout would be similar to the following:
<img width="952" alt="image" src="https://github.com/user-attachments/assets/b6afb9cc-3c64-4576-b13c-3409e09a2f6b">

Thanks!!!

**Comment by jeevan10017** [comment]
@Jay-1409 Ok go ahead. Don't make the same cards; make creative ones. The cards and backgrounds should match the website theme.

**Comment by Jay-1409** [comment]
Ok on it!!
