### ISSUE TITLE
[Feature Request]: I want to add a contributing page through github api

### ISSUE THREAD

**Issue by souvikpramanikgit** [Open-Code-Crafters/FitFlex#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a contributing page in website through github api.

### Use Case

It shows how many people contribute in this project as it a open source project. And also showing how many contribution can be done by particular contributor.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/38107d74-b551-4a24-8bf2-feac8fa154b0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@souvikpramanikgit, some one is already working on it, please go through it.
