### ISSUE TITLE
[Bug]: Text is not visible properly in this page

### ISSUE THREAD

**Issue by souvikpramanikgit** [Open-Code-Crafters/FitFlex#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text is not visible properly in this page

### Expected behavior

I want to add some style to solve this problem.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/382590fd-1304-4123-a0c2-c2bcaa287b60)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@souvikpramanikgit, this issue has already been assigned to someone.

Thank you for your contribution
