### ISSUE TITLE
Correct Services Card Text

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Open-Code-Crafters/FitFlex#430]
**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

The services page cards text, views and likes are not properly set. I want to correct it.
![image](https://github.com/user-attachments/assets/eb79678b-f387-42a3-b1dd-309c794f5ebe)

**Comment by GAVINESHWAR** [comment]
@AnushkaChouhan25, please complete as soon as possible.
