### ISSUE TITLE
[FEATURE] : Integration of Gemini AI Chatbot for Fitness Guidance and Support

### ISSUE THREAD

**Issue by Shariq2003** [Open-Code-Crafters/FitFlex#432]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Feature Description

To improve user engagement and provide immediate, personalized support, I propose integrating the Gemini AI Chat into the FitFlex platform. This Chat will assist users with workout guidance, fitness tips, nutrition advice, and provide motivational support to keep users consistent in their fitness journey.

The Gemini AI chatbot will be customized to match the FitFlex website's theme, ensuring a cohesive look and user experience.

### DEMO

![image](https://github.com/user-attachments/assets/488aa79f-4969-4bc0-bdef-ec446e53df75)

### Use Case

1. **Enhanced User Guidance**: The Gemini AI chatbot will provide immediate answers to common questions about workout routines, exercise techniques, and general fitness guidance, creating a more supportive and educational experience for users.

2. **Personalized Fitness Advice**: Users can quickly get personalized advice on exercises, diet, and fitness routines tailored to their goals (e.g., weight loss, muscle gain, general fitness), empowering them to make well-informed choices.

3. **24/7 Availability**: With round-the-clock access, users can receive support and encouragement anytime, which is especially valuable for maintaining motivation and adherence to fitness goals.

### Benefits

- **Improved User Retention**: Real-time assistance encourages users to stay engaged and on track with their fitness programs.
- **Enhanced User Experience**: The chatbot adds a layer of personalized guidance, making FitFlex feel like a more interactive and supportive fitness companion.
- **Resource Efficiency**: By answering frequently asked questions, the chatbot reduces the need for additional human support, allowing for more efficient resource allocation.

### Priority
High

### Checklist
- [X] I have read the Contributing Guidelines
- [X] I’m a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Shariq2003,  please complete as soon as possible.

**Comment by Shariq2003** [comment]
@GAVINESHWAR sir, please look into level

**Comment by Shariq2003** [comment]
@GAVINESHWAR sir, I am adding Both, Backend and Frontend
