### ISSUE TITLE
[Bug]: 🐞Next/Previous Button Design Issues

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Open-Code-Crafters/FitFlex#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The next and previous buttons have inconsistent sizing and appearance:

- When hovered or clicked, the buttons become too small.
- Without hovering, they appear too large.
- The arrow icon inside the buttons is not visible, impacting usability and design consistency.

### Expected behavior

N/A

### Add ScreenShots

![image](https://github.com/user-attachments/assets/04efec8a-4b12-4859-b1ce-834b6dc06568)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@AnushkaChouhan25, please complete as soon as possible.

**Comment by AnushkaChouhan25** [comment]
@GAVINESHWAR Done
