### ISSUE TITLE
Design Issue with Next/Prev Buttons

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Open-Code-Crafters/FitFlex#435]
**Description**
The design of the next and previous buttons in the "Meet Our Team" section has inconsistencies. When hovered or clicked, the buttons become too small, and the arrow icon is not clearly visible. Without hover, the buttons appear overly large, which affects the overall aesthetics.

**Expected Behavior**
The next and previous buttons should maintain a consistent size with a clear arrow icon. On hover, the size should slightly change or have a subtle effect, but not drastically reduce in size, ensuring a visually appealing and functional navigation experience.

**Screenshot**
![image](https://github.com/user-attachments/assets/7a8b6847-d8bd-4bab-8b74-e902b58cedd4)

**Comment by GAVINESHWAR** [comment]
@AnushkaChouhan25, please complete as soon as possible.

**Comment by AnushkaChouhan25** [comment]
@GAVINESHWAR Done
