### ISSUE TITLE
[Feature Request]: Stargazers Timeline Animation

### ISSUE THREAD

**Issue by yashksaini-coder** [Open-Code-Crafters/FitFlex#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a stargazers timeline animation, which is generated using the remotion library. To create a a rendering component that will be used to render the **main.mp4** file, for the stargazers timeline animation.

### Use Case

To be able to showcase the performance & journey of the project.

### Add ScreenShots

[designdeck-234.webm](https://github.com/user-attachments/assets/ca4a4764-9f6b-4cbf-81b9-da15e6310f5f)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
@GAVINESHWAR Can you assign me this issue for Level 3

**Comment by GAVINESHWAR** [comment]
@yashksaini-coder, please proceed
