### ISSUE TITLE
[Bug]: Card button is not looking good

### ISSUE THREAD

**Issue by Hemraj-7** [Open-Code-Crafters/FitFlex#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the blog page cards button is not looking good.

![Screenshot 2024-11-07 163914](https://github.com/user-attachments/assets/eeb50a01-dcbe-44ef-a18f-561d1b1e38e4)
![Screenshot 2024-11-07 164031](https://github.com/user-attachments/assets/6d1ede18-e549-4f8b-ab82-fb0d3e77061f)

I want to make is better.
Assign me this issue 

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Hemraj-7, please complete as soon as possible.

**Comment by Hemraj-7** [comment]
> @Hemraj-7, please complete as soon as possible.

yeah sure!
