### ISSUE TITLE
[Feature Request]: Remotion setup for stargazers

### ISSUE THREAD

**Issue by yashksaini-coder** [Open-Code-Crafters/FitFlex#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to setup a sub react application to use remotion for the stargazers animation.

### Use Case

This will be used to setup a baseline for the animation generation of the stargazers, later it will be automated

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
@GAVINESHWAR Kindly, can you assign me this issue.

**Comment by GAVINESHWAR** [comment]
@yashksaini-coder, please complete as soon as possible.
