### ISSUE TITLE
Implement subscribe to our Newsletter Functionality 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
![Screenshot 2024-11-07 234347](https://github.com/user-attachments/assets/7c46e111-afc8-495b-80f1-2bb07cde19c2)

We need to implement a newsletter subscription functionality on our platform, fitflex. This feature will allow users to enter their name and email to subscribe to our newsletter. Upon successful subscription, users will receive a confirmation email.

### Use Case

https://github.com/user-attachments/assets/7f0d2e9b-cb3d-4051-a12a-276453ef8409

### Benefits

Once subscribed, users receive a welcome email with details about the platform and its offerings.

Also saved the details of the user in the database for future !!

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, please complete as soon as possible.
