### ISSUE TITLE
Enhance styling of blog page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Open-Code-Crafters/FitFlex#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/user-attachments/assets/ad4a18dd-270e-41e5-b173-fa5510053b89)

it is not looking good 

### Use Case

![image](https://github.com/user-attachments/assets/799da630-aaab-433d-8e07-9353b1ae5723)

 i can enhance its styling to look like this 
 and redesign it according to our website theme

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Sawan-Kushwah, please complete as soon as possible.
