### ISSUE TITLE
[Bug]: Log In Page eye button glitch

### ISSUE THREAD

**Issue by vanshikag1410** [Open-Code-Crafters/FitFlex#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Invalid passwords shifts the eye button sometimes. Also when eye button is on the password is hidden and when off then it is shown. These glitches have to be fixed.

### Expected behavior

Should show password only when the button is turned on.

### Add ScreenShots

![Screenshot from 2024-11-08 07-35-49](https://github.com/user-attachments/assets/82ec432b-cf10-4df8-af46-1f787258cf82)
![Screenshot from 2024-11-08 07-36-05](https://github.com/user-attachments/assets/0418db0b-2ad1-4b49-a144-3df90542c071)

### On which device are you experiencing this bug?

Linux

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@vanshikag1410, please complete as soon as possible.
