### ISSUE TITLE
[Bug]: NOT DISPLAY

### ISSUE THREAD

**Issue by Meetpidev** [Open-Code-Crafters/FitFlex#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

SOCIAL ICONS ARE NOT DISPLAYED

### Expected behavior

IT SHOULD BE DISPLAY

### Add ScreenShots

![image](https://github.com/user-attachments/assets/69692d7b-3667-4cb1-b7d8-229e96a6bd11)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Meetpidev** [comment]
@jeevan10017 Can i do this ?

**Comment by GAVINESHWAR** [comment]
@Meetpidev, please complete as soon as possible.

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR that isent #409 #401

**Comment by Meetpidev** [comment]
@GAVINESHWAR Please Review PR #401 and #467
