### ISSUE TITLE
[Bug]: Issue in plan.jsx here yoga positions not there profer card so the text is not getting fixed 

### ISSUE THREAD

**Issue by Rohan1786** [Open-Code-Crafters/FitFlex#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Issue in plan.jsx here yoga positions not there profer card so the text is getting not fixed

### Expected behavior

so i can fixed that please assign it to me

### Add ScreenShots

https://github.com/user-attachments/assets/2cf3e05a-dcac-43bf-b8bf-903a0b217a3d

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@Rohan1786 , please complete as soon as possible.

**Comment by Rohan1786** [comment]
By mistakally i removed assign me please add and check my pull request i did he task

**Comment by Rohan1786** [comment]
Assign me and closed this task i contributed this task i completed and fix the bug
