### ISSUE TITLE
[Feature Request]: Setting up the Stargazers application in Remotion

### ISSUE THREAD

**Issue by yashksaini-coder** [Open-Code-Crafters/FitFlex#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding all the necessary application files used to render and generate the main stargazers animation

### Use Case

This is the main application files that are required by the main application

### Benefits

This main application can be executed by simply making your way into the `/stargazers` folder, and running the `npm run dev` command in the cli. 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
@GAVINESHWAR kindly assign me this for level 3 at least

**Comment by GAVINESHWAR** [comment]
@yashksaini-coder, please complete as soon as possible.
