### ISSUE TITLE
[Feature Request]: Final Application test & generation of the Stargazers animation

### ISSUE THREAD

**Issue by yashksaini-coder** [Open-Code-Crafters/FitFlex#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature will be used to final complete the stargazers application that allows the generation of the stargazers animation.

### Use Case

For automation purposes, of the stargazers animation.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9ad450fe-9385-4eff-920d-7bd537713f13)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by yashksaini-coder** [comment]
@GAVINESHWAR Kindly assign me this issue for level 3 if possible

**Comment by GAVINESHWAR** [comment]
@yashksaini-coder, please complete as soon as possible.
