### ISSUE TITLE
[Feature Request]: Lack of User Testimonials or Social Proo

### ISSUE THREAD

**Issue by ROHAN7051** [Open-Code-Crafters/FitFlex#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There's no visible social proof (like testimonials or user reviews), which might reduce trust in the effectiveness of the plans.

### Use Case

this feature will help the app to standout from the crowd and also show the benefits and success stories of purchasing the product

### Benefits

 Add testimonials, reviews, or success stories to build credibility and encourage conversions.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@ROHAN7051 updates?

**Comment by ROHAN7051** [comment]
i am working on it i will ping u as soon as i done with it sorry for delay ;)

**Comment by ROHAN7051** [comment]
@jeevan10017  i am done with the feature

**Comment by jeevan10017** [comment]
> @jeevan10017 i am done with the feature

Raise PR
