### ISSUE TITLE
[Bug]: Log In broken link from register page

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Open-Code-Crafters/FitFlex#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Encountered a broken link on the Register page when attempting to navigate to the Log In page. Clicking the "Sign In" button results in a "Page Not Found" error, displaying the message: "Looks like you've followed a broken link or entered a URL that doesn't exist on this site." This issue prevents users from accessing the login functionality, hindering the registration process.

### Expected behavior

When a user clicks on the "Sign In" button from the Register page, they should be redirected to the Log In page without any errors. The Log In page should load correctly, allowing users to enter their credentials and access their accounts.

### Add ScreenShots

![Screenshot 2024-10-04 155441](https://github.com/user-attachments/assets/434c97b0-63f4-4495-aa9b-8d6ea8f341dd)
![Screenshot 2024-10-04 155515](https://github.com/user-attachments/assets/bb065c03-5434-4226-b8cf-a5284d9e6937)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@AbhijitMotekar99 go ahead!
