### ISSUE TITLE
[Feature Request]: Enhancing the coloring of Contact us form

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Open-Code-Crafters/FitFlex#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Request to enhance the coloring of the "Contact Us" form. Currently, the form features a greenish color that does not align with the overall color scheme of the website. A more cohesive color palette should be implemented to ensure visual consistency and improve the overall aesthetic of the form, making it more appealing and user-friendly.

### Use Case

1. User Experience: When users visit the website, they should encounter a "Contact Us" form that is visually harmonious with the site's overall design. This encourages users to engage with the form rather than feeling distracted or confused by mismatched colors.

2.  Visual Appeal: The enhanced coloring will help draw attention to the form, making it more inviting for users to submit inquiries, feedback, or requests for support.

4. Brand Consistency: Aligning the form’s color with the website’s theme reinforces brand identity and creates a professional appearance, which can increase user trust and satisfaction.

### Benefits

- Improved User Engagement: A visually appealing and consistent "Contact Us" form will encourage more users to fill it out, leading to increased interactions and feedback.

- Enhanced Aesthetics: Aligning the form's colors with the overall website theme creates a more cohesive look, enhancing the site's 

- Increased Trust: A well-designed form can build user trust and confidence in the website, making users more likely to share their information or inquiries.

- Better Brand Identity: Consistency in design elements reinforces brand identity and recognition, making it easier for users to associate the form with the website and its purpose.

- Higher Conversion Rates: A user-friendly and attractive form can lead to higher conversion rates, as users are more likely to complete the form if it is visually appealing and easy to understand.

### Add ScreenShots

![Screenshot 2024-10-04 155917](https://github.com/user-attachments/assets/4a4b5adc-2324-4945-b4d0-835dd31774b0)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@AbhijitMotekar99 go ahead!
