### ISSUE TITLE
[Bug]: horizontal scrolling

### ISSUE THREAD

**Issue by ak3264114** [Open-Code-Crafters/FitFlex#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a horizontal scrolling in the website

### Expected behavior

i can make sure that the horizontal scrolling should removed

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f6d9080a-032a-4a03-9e2b-7b061382d170)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@ak3264114 updates?
