### ISSUE TITLE
[Feature Request]: Add Toggle button to switch between dark and light mode

### ISSUE THREAD

**Issue by Shreya-Pandey-01** [Open-Code-Crafters/FitFlex#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add Toggle button to switch between dark and light mode , it enriches the user experience

### Use Case

when using at night ,the dark mode will act beneficiary for the eyes

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Shreya-Pandey-01** [comment]
pls. assign this issue to me, I'd love to work on it

**Comment by jeevan10017** [comment]
@Shreya-Pandey-01 Go ahead, I May upgrade your level based on your Work.

**Comment by Shreya-Pandey-01** [comment]
ok sir, thank you for assigning

**Comment by jeevan10017** [comment]
@Shreya-Pandey-01 updates?

**Comment by Shreya-Pandey-01** [comment]
half is done sir, still working on it
