### ISSUE TITLE
[Feature Request]: Firebase Authentication using email id/Ph no and password

### ISSUE THREAD

**Issue by samriddhitiwary** [Open-Code-Crafters/FitFlex#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature request is for integrating Firebase Authentication into the project, allowing users to log in using their email and password. Firebase's simple authentication system would enable secure user management with minimal setup.

It should also send the email verification to the user.

### Use Case

This feature would be beneficial for projects that require user authentication and account creation. By implementing Firebase Authentication, users can securely log in and create accounts using their email and password. This is useful for e-commerce platforms, personal dashboards, or any web application requiring account-based interaction.

### Add ScreenShots

Simplifies user authentication and management
Provides a secure, scalable, and easy-to-implement solution for user login
Reduces development time by using Firebase's built-in authentication methods
Enhances user experience by offering a reliable sign-in option

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by samriddhitiwary** [comment]
@jeevan10017 Could please assign this issue to me under the GSSoC-exd and Hacktoberfest label

**Comment by samriddhitiwary** [comment]
@jeevan10017 I will start working on this

**Comment by jeevan10017** [comment]
@samriddhitiwary updates, do you need any help?

**Comment by samriddhitiwary** [comment]
@jeevan10017 Actually I have an exam coming this week that's why it's bit difficult to manage it.
Yes can you please assign someone else to, so that we can work together

**Comment by jeevan10017** [comment]
@isimarjitsingh

**Comment by jeevan10017** [comment]
> @isimarjitsingh, I am assigning you too in this work. You both can work on this.

follow up this message if you want to do so

**Comment by isimarjitsingh** [comment]
Yes, I have already added authentication to it. Assign this issue to me.
