### ISSUE TITLE
[Feature Request]: fixing UI and creating local data storage✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Open-Code-Crafters/FitFlex#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to improve this UI , as it can be improved.
I will create a localdatabase to store the signin details.

Can u please assign me this task so i can work on it. can u tag the level aswell.
Thank you!

### Add ScreenShots

<img width="807" alt="Screenshot 2024-10-05 at 9 50 32 PM" src="https://github.com/user-attachments/assets/6936d530-fa2a-450e-b0c1-c0240a31921e">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@T-Rahul-prabhu-38 Someone has already worked on UI Enhancement. And sign-in credentials will be stored in Firebase.

**Comment by T-Rahul-prabhu-38** [comment]
no this isnt for credentials, this will be for JWT's

**Comment by jeevan10017** [comment]
@T-Rahul-prabhu-38 yeah, some one working on same issue #18
