### ISSUE TITLE
[Bug]: Remove the unnecessary scroll bar 

### ISSUE THREAD

**Issue by ananyag309** [Open-Code-Crafters/FitFlex#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![oiuytrewq](https://github.com/user-attachments/assets/6003a131-60fe-463f-9a52-4ac92e585b16)

### Expected behavior

remove it for better and professional outlook

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@ananyag309 I appreciate your interest👏. However, someone is already working on this (issue - #52 ). You can raise another issue. Kindly review the currently active issues.
