### ISSUE TITLE
[Feature Request]:  Add Comment and Like Buttons to Blog Section

### ISSUE THREAD

**Issue by SCR01** [Open-Code-Crafters/FitFlex#62]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to request the addition of comment and like buttons in the blog section of our application. This will allow users to engage with the content more effectively by leaving comments and showing appreciation through likes.

### Use Case

Adding comment and like buttons would create a more interactive experience for users. For instance, users can express their thoughts about a specific blog post and interact with other users, fostering a community around the blog.

### Benefits

- **User Engagement**: Users will feel more connected to the content, leading to increased engagement and return visits.
- **Feedback Loop**: Comments can provide valuable feedback to content creators regarding what users enjoy or want to see more of.
- **Community Building**: Encouraging discussions in the comments can build a community around the blog, enhancing user retention.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Nandinig24** [comment]
Please assign the task to me!

**Comment by kushal7201** [comment]
@SCR01 I would like to work on the issue. Kindly assign it to me.
