### ISSUE TITLE
[Feature Request]: Add Packages Section for Different Fitness Packages

### ISSUE THREAD

**Issue by SCR01** [Open-Code-Crafters/FitFlex#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose adding a "Packages" section to our application where we can present various fitness packages. This could include options for different training durations, nutrition plans, and group classes tailored to different fitness levels.

### Use Case

This feature will allow users to easily compare and select packages that best suit their fitness goals and needs. It will provide clarity and simplify the decision-making process for potential clients.

### Benefits

- **Improved User Experience**: Users will have a clear view of available packages, making it easier to choose a suitable plan.
- **Attract More Clients**: Well-defined packages can attract more users, as they will see the value and variety offered.
- **Simplified Marketing**: It allows for targeted marketing of specific packages during promotions or seasonal offers.

### Add ScreenShots

![Screenshot 2024-10-06 033347](https://github.com/user-attachments/assets/4996b75c-0e9d-442a-a3d4-3ebff08f3c7b)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by SCR01** [comment]
@jeevan10017 can you assign this to me, now?

**Comment by kushal7201** [comment]
@SCR01 I would like to work on the issue. Kindly assign it to me.
