### ISSUE TITLE
✨[Feature Request]: Improve the contact us UI and add backend functionality.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Open-Code-Crafters/FitFlex#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- i will fix the UI of this page.
- i will add a local storage access to store the user inputted credentials.

### Use Case

- this is especially very important as this can be used to retrieve the information.
- this can also be used to store JWT's which helps us with logged in cache.

### Add ScreenShots

<img width="801" alt="Screenshot 2024-10-06 at 9 57 47 AM" src="https://github.com/user-attachments/assets/466161d1-821c-4c22-8f76-d8b4e2395662">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Nandinig24** [comment]
Please assign the task to me as a hacktoberfest contributor

**Comment by kushal7201** [comment]
@T-Rahul-prabhu-38  I would like to work on the issue. Kindly assign it to me.

**Comment by jeevan10017** [comment]
@Nandinig24 Sorry, I had worked already. If you want to do more. Kindly create new issue
