### ISSUE TITLE
[Feature Request]: Making about us page good looking and also add some dummy stats showing on scroll up animation

### ISSUE THREAD

**Issue by VinayLodhi1712** [Open-Code-Crafters/FitFlex#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

About us page UI is not good looking so i want to redesing it with same content also want to show dummy stats like total user and all on scroll up animation on about us page

### Use Case

Good UI design

### Add ScreenShots

![about page ui](https://github.com/user-attachments/assets/e09b50e4-e1a3-4217-a5fc-ed4b91a55a3a)

Uploading 20241006142647.mp4…

plz add level on it so i can start working on it.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Sami3160** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Feature Description
> 
> About us page UI is not good looking so i want to redesing it with same content also want to show dummy stats like total user and all on scroll up animation on about us page
> ### Use Case
> 
> Good UI design
> ### Benefits
> 
> _No response_
> ### Add ScreenShots
> 
> ![about page ui](https://private-user-images.githubusercontent.com/135756009/373935710-e09b50e4-e1a3-4217-a5fc-ed4b91a55a3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTkzMjIsIm5iZiI6MTcyODIxOTAyMiwicGF0aCI6Ii8xMzU3NTYwMDkvMzczOTM1NzEwLWUwOWI1MGU0LWUxYTMtNDIxNy1hNWZjLWVkNGI5MWE1NWEzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMjUwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTdlM2Y5YWY0OWE2MTJlYzE5YzUzNjkxZGM5ZGFmNTkwOTZhMzFlMzdiODQyMTY1YmZkMTRjYjkxMzFmMTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Wn_6abJfDwkEkypE1jD8Cqb_bJTdY5nKpOJH00RTTYE)
> 
> Uploading 20241006142647.mp4…
> 
> plz add level on it so i can start working on it.
> ### Priority
> 
> High
> ### Record
> 
>     * [x]  I have read the Contributing Guidelines
> 
>     * [x]  I'm a GSSOC-EXT contributor
> 
>     * [x]  I'm a HACKTOBERFEST contributor
> 
>     * [x]  I have starred the repository

go ahead,

**Comment by VinayLodhi1712** [comment]
add level also so that it will help me to get score on gssoc leaderboard and i am starting work on it

**Comment by Sami3160** [comment]
> add level also so that it will help me to get score on gssoc leaderboard and i am starting work on it

for now, ill add lvl1, after watching your work ill change
