### ISSUE TITLE
[Bug]: Github , linkedln and email links are not working on the footer

### ISSUE THREAD

**Issue by Monu2114** [Open-Code-Crafters/FitFlex#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The User is not able to view github and other links 

### Expected behavior

The user can be able to visit the links and communicate with the developers of app 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5bc56f88-c642-4b53-827f-34fd65b6ff15)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@Monu2114 go ahead!

**Comment by jeevan10017** [comment]
@Monu2114 update ?

**Comment by Monu2114** [comment]
Hey am working on it. Had exams till today so couldn't do. Will do it soon

**Comment by harshbhar0629** [comment]
Can I work on this issue???
