### ISSUE TITLE
[Bug]: Footer Link Not Navigating to desired Section

### ISSUE THREAD

**Issue by Vaishh18** [Open-Code-Crafters/FitFlex#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking the FAQ link in the footer:

Current Behavior: The page does not scroll to or display the FAQ section. The link seems inactive, providing no feedback or redirection.

### Expected behavior

The page should smoothly scroll down to the FAQ section, allowing users to view the frequently asked questions without manual scrolling. 

### Add ScreenShots

As you can see in the video after clicking on FAQ it doesnt navigate to FAQ section.

https://github.com/user-attachments/assets/cb30bdcc-cd87-41a3-9fb5-ebdb7039a2d7

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Vaishh18** [comment]
Hey, @jeevan10017 Please assign me this issue ,I would like to work on it

**Comment by jeevan10017** [comment]
@Vaishh18  fix all links on the website, login... and verify all the links

**Comment by jeevan10017** [comment]
Sorry, upper reference by mistake

**Comment by Vaishh18** [comment]
@jeevan10017 Yess,I will do it.

**Comment by jeevan10017** [comment]
@Vaishh18 any updates?
