### ISSUE TITLE
[Feature Request]: Integrating Email sending backend for contact us.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [Open-Code-Crafters/FitFlex#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The integration of an email-sending backend for the "Contact Us" section would allow users to submit their inquiries, feedback, or support requests through a web form. Upon submission, an email would be sent to the designated recipient (e.g., the support team or a specific email address), ensuring prompt communication and response.

### Use Case

1. User Interaction: A user fills out the "Contact Us" form, providing their name, email address, subject, and message.
2. Form Submission: Upon clicking the "Send" button, the form data is sent to the backend.
3. Email Sending: The backend processes the request and sends an email to the specified recipient, notifying them of the new inquiry.
4. User Feedback: An acknowledgment message is displayed to the user confirming that their message has been sent successfully.

### Benefits

1. Enhanced User Experience:

- Convenience: Users can easily submit their inquiries or feedback without having to navigate away from the website, ensuring a seamless experience.
- Quick Acknowledgment: Automated email responses can reassure users that their messages have been received and are being addressed.

2. Efficient Communication:

- Direct Interaction: Establishes a direct line of communication between users and the support team, facilitating quicker resolutions to issues or questions.
- Prioritization of Inquiries: The support team can categorize and prioritize incoming emails, allowing for more effective management of user requests.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@AbhijitMotekar99  It has already been done.
