### ISSUE TITLE
Responsive Design Optimization

### ISSUE THREAD

**Issue by samriddhitiwary** [Open-Code-Crafters/FitFlex#8]
Improving Website Responsiveness with ReactJS and CSS for Enhanced User Experience

**Comment by jeevan10017** [comment]
@samriddhitiwary can you specify, which part/page you want to work with, 
give bug/enhancement with a video/image for reference with the following description.

**Comment by samriddhitiwary** [comment]
Instead of this issue, I have raised another one regarding the login page. I would really appreciate it if you could assign that one to me for now. I also apologize for creating this issue in the first place @jeevan10017
