### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by isimarjitsingh** [Open-Code-Crafters/FitFlex#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description Sign In validation, designing, redux for profile

 As your login page does not working on the basis of validation ,please give me that work  whereas i will concentrate on authentication , redesigning  and as well as i will show the name of the user on your home page with the help of redux-toolkit .
i will provide email and password authentication with the help of firebase google tool.

### Use Case

example:- if a old user wanna starts where he/she exits it will start from that point that's why authentication is verry important thing,
and a good designing always reflect your website ideas also .

### Benefits

it makes your website more interactive and proffesional , so please assign me this work  .so i will looking forward to contribute in it :).

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@isimarjitsingh at present #57, is working on it. i will let you know after it completes.
