### ISSUE TITLE
Issue: Redesign Footer Section for Better Aesthetics and Functionality

### ISSUE THREAD

**Issue by satyasootar** [Open-Code-Crafters/FitFlex#85]
### **Proposal:**
The current footer design can be improved to enhance its visual appeal and usability. I would like to redesign the footer section to make it more engaging, aligned with the website's overall design, and include additional useful links or features.
![image](https://github.com/user-attachments/assets/d575c999-9247-431a-be8b-345ae571cfab)

### **Expected Outcome:**

-A modern, clean footer design with better alignment, spacing, and styling.
-Enhanced layout, including proper sections for About Us, Useful Links, Social Media, and Contact Information.
-Improved typography for better readability and use of consistent icons for social media and other interactive elements.
-A responsive design that adjusts smoothly across devices.
![image](https://github.com/user-attachments/assets/199506c7-56af-49a4-a660-098c3bfc6697)
I will take the reference from this and add the asthetics from your page including the logo

**Comment by jeevan10017** [comment]
@satyasootar go ahead 👍
