### ISSUE TITLE
[Feature Request]:  Copyright is not available 

### ISSUE THREAD

**Issue by Anjalis14** [Open-Code-Crafters/FitFlex#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

copyright for thw websitw is needed so ill add copyright to it

### Use Case

it will enhance the look of the project 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Anjalis14** [comment]
@jeevan10017 plz assign me this

**Comment by jeevan10017** [comment]
@Anjalis14 Its present already, someone has worked on this while this issue raised. try to find out new issues/features.
