### ISSUE TITLE
[Feature Request]: Adding newsletter 

### ISSUE THREAD

**Issue by govindumeesala** [Open-Code-Crafters/FitFlex#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding newsletter increases more connectivity between the users and owners.

### Use Case

It helps users to get notifications and updates about website. 
which gives more reach to the website.

### Benefits

More connectivity between the client and the owner

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by govindumeesala** [comment]
@jeevan10017 please assign me this

**Comment by jeevan10017** [comment]
@govindumeesala #85 is working on the same.
