### ISSUE TITLE
After Register not redirect to login page

### ISSUE THREAD

**Issue by Pushpa472** [Open-Code-Crafters/FitFlex#88]
@jeevan10017 I see that after registration, it does not redirect to the login page.
![image](https://github.com/user-attachments/assets/7e277477-8270-4264-856f-b976f8b0af21)

**Comment by jeevan10017** [comment]
@Pushpa472 linking doesn't counts under contribution. Try to find more issues/bugs/ features  and integrate it 
Thank you

**Comment by Pushpa472** [comment]
ok
