### ISSUE TITLE
Add functionality to "JOIN FITFLEX NOW" button at about us page

### ISSUE THREAD

**Issue by ananyag309** [Open-Code-Crafters/FitFlex#89]
right now the button is not functional i guess when we click on that button it should navigate us to register page 

![image](https://github.com/user-attachments/assets/0d04c6cd-9d47-4a2f-a6f5-b4de53ec7c81)

**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

**Comment by jeevan10017** [comment]
Adding a link can't be added as a contribution as per the rules of gssoc-ext and hactoberfest.

**Comment by ananyag309** [comment]
I raised one more issue can I merge and make them a single issue ?

**Comment by vanshika704** [comment]
i have added the required functionalities along with some enhancement in button on hover conditions . and the navigation through the button is working too
