### ISSUE TITLE
Improve README with Contribution and Installation Steps

### ISSUE THREAD

**Issue by akshadgujarkar** [Open-Code-Crafters/FitFlex#9]
This issue addresses the need to improve the clarity and structure of the README file by adding contribution and installation instructions to make it easier for new developers to get started with FitFlex.

**Comment by akshadgujarkar** [comment]
can u assign this issue to me I am really wanna work on it

**Comment by jeevan10017** [comment]
@akshadgujarkar go ahead

**Comment by akshadgujarkar** [comment]
@jeevan10017  could you pls review the changes I made in my forked repository 
Link :- https://github.com/akshadgujarkar/FitFlex

**Comment by jeevan10017** [comment]
@akshadgujarkar Make the content more visually appealing by including website pages' descriptions and using icons instead of all in plain text.

**Comment by jeevan10017** [comment]
Ok go ahead, send PR
