### ISSUE TITLE
[Bug]: Register button should be highlighted 

### ISSUE THREAD

**Issue by 4F24L** [Open-Code-Crafters/FitFlex#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Bug Info : 
- Register button should be highlighted along with the navigation elements.
- The register button should stand out in the navigation bar.

### Register button styles should be added : 
- border
- background color
- separate hover effect

### Add ScreenShots

![image](https://github.com/user-attachments/assets/86f21d51-6460-4f8f-b143-de2ecdfa15ca)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by jeevan10017** [comment]
@4F24L Designing a button doesn't count under contribution. Try to find out more issues and merge it.

**Comment by jeevan10017** [comment]
@4F24L go ahead.
