### ISSUE TITLE
the button in the about page isnt working . i have the approach for the same including the enhancement of the hover button .

### ISSUE THREAD

**Issue by vanshika704** [Open-Code-Crafters/FitFlex#94]
**Contributor Information**
the button was not navigating to register page and the hover was set to blue that was not good looking .

**Comment by jeevan10017** [comment]
@vanshika704 As per the rules, don't work on the issue if it is not assigned.

**Comment by jeevan10017** [comment]
> @vanshika704 As per the rules, don't work on the issue if it is not assigned.

and also, changing the colouring of the button doesn't count under contribution.

**Comment by vanshika704** [comment]
sir , i didnt change the color as the main contribution . the button was not working and thats what i improved .. as per the mentioned message .

**Comment by vanshika704** [comment]
also , as a contributer to the code , i found your way of telling about the comment quite strange . i was expecting you to atleast see the whole comment once

**Comment by jeevan10017** [comment]
> also , as a contributer to the code , i found your way of telling about the comment quite strange . i was expecting you to atleast see the whole comment once

Yeah, I mean changing the styling and linking it doesn't worth for the contribution, and it should be waited for until you get assigned.
