### ISSUE TITLE
Redesigning the Service page and contact form

### ISSUE THREAD

**Issue by say-het** [Open-Code-Crafters/FitFlex#98]
Hey @jeevan10017,

 I would like to redesign these things so that they match perfectly with the theme of the website
 
1. Services page
2. This contact form
![image](https://github.com/user-attachments/assets/b9a8ac01-3207-4ab2-9f30-92fe10606459)

Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

 - Little about me: I am an experienced contributor as I have successfully completed Hacktoberfest-2020, Hacktoberfest-2023 and GSSoC-2024.

**Contributor Information**
Please check if you are a contributor from:
- [x] GSSoC-ext
- [x] Hacktoberfest

**Comment by say-het** [comment]
This page 

![Screenshot_2024-10-08-06-51-03-497_com android chrome](https://github.com/user-attachments/assets/8565d7b7-950a-49a3-aa41-288f12aec630)

**Comment by jeevan10017** [comment]
@say-het go on it.
