### ISSUE TITLE
add chatbox

### ISSUE THREAD

**Issue by Codewithmeowmeow** [Open-Code-Crafters/FitFlex#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a chatbox where users can ask basic doubts.

### Use Case

In solving doubts.

### Benefits

Implementing this feature will make the website more interactive and increase peoples engagement

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by Sawan-Kushwah** [comment]
@jeevan10017 can I work on this?
